#!/usr/bin/env python3
"""free_head_finalize.py -- BUILD 1: assemble the round artifact.

Merges
  results/cascade_methods/artifacts/_free_head_parts/selectors.json    (part A, CPU)
  results/cascade_methods/artifacts/_free_head_parts/equivalence.json  (part D, CPU, needs the captures)
into
  results/cascade_methods/artifacts/free_head_2026-08-16.json

No number is computed here that is not already in a part file; this only organises and states the
verdict, so the verdict cannot disagree with the measurements.
"""
from __future__ import annotations

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
import genframe_data as G   # noqa: E402

PARTS = os.path.join(G.ROOT, "results/cascade_methods/artifacts/_free_head_parts")
OUT = os.path.join(G.ROOT, "results/cascade_methods/artifacts/free_head_2026-08-16.json")


def v(d, *ks, default=None):
    for k in ks:
        if d is None:
            return default
        d = d.get(k) if isinstance(d, dict) else None
    return default if d is None else d


def main():
    A = json.load(open(os.path.join(PARTS, "selectors.json")))
    B = json.load(open(os.path.join(PARTS, "equivalence.json")))

    arms = B["arms"]
    eq = B["equivalence"]
    cmpB = B["comparisons"]

    def arm(nm):
        a = arms.get(nm)
        if a is None:
            return None
        return {k: a[k] for k in ("sel_eff_judge", "selected_judge", "sel_eff_em", "selected_em",
                                  "oracle_judge", "oracle_em", "slot_coverage", "per_ds")}

    out = {
        "title": "BUILD 1 -- MAKE THE HEAD FREE.  Capturing the generator-frame hidden states during "
                 "generation instead of recomputing them with a teacher-forced pass",
        "date": "2026-08-16",
        "no_fabricated_numbers": True,
        "objective": "The new round objective is 'a small trained verifier improves a 7B medical VLM "
                     "by +X on N cells at Y x the 7B's own compute'.  The generator-frame head costs "
                     "3.813646 forward passes per question (= 8943 distinct normalised answers / 2345 "
                     "questions) purely to recompute hidden states the generator already produced. "
                     "This build tests whether capturing them during generation reproduces the head's "
                     "scores and picks, and what that removes from Y.",
        "reproduce": [
            "python3 src/training_methods/free_head_selectors.py",
            "HF_HOME=/data/dan/hf_cache CUDA_VISIBLE_DEVICES=0 python3 src/training_methods/free_head_capture.py --cap cap320  --out feats_free",
            "HF_HOME=/data/dan/hf_cache CUDA_VISIBLE_DEVICES=1 python3 src/training_methods/free_head_capture.py --cap fullres --out feats_free",
            "python3 src/training_methods/free_head_analyze.py",
            "python3 src/training_methods/free_head_finalize.py"],
        "code": ["src/training_methods/free_head_lib.py",
                 "src/training_methods/free_head_capture.py",
                 "src/training_methods/free_head_selectors.py",
                 "src/training_methods/free_head_cost.py",
                 "src/training_methods/free_head_analyze.py",
                 "src/training_methods/free_head_finalize.py"],
        "endpoint": {
            "pool": "the frozen 2345-question open-text best-of-8 pool (slake_open 645 / vqa_rad_open "
                    "200 / pathvqa_open 1500), 1468 recoverable, generated by Lingshu-7B at T=0.7, "
                    "cap320, vLLM (runners/run_openvqa_lingshu7b.sh, runners/run_openvqa_pathvqa.sh)",
            "metric": "src/training_methods/genframe_data.py (frozen), argmax with first-index tie-break",
            "selector": "ckpts/train/genframe_head_ens8 (frozen 8-seed head) + "
                        "ckpts/train/lora_verifier_disjoint (frozen clean LoRA verifier)",
            "currencies": A["currencies"]},

        "null_tests": dict(B["null_tests"], **{
            "harness_reproduces_the_frozen_feature_cache": {
                "what": "does THIS capture harness's FULLRES teacher-forced pass reproduce "
                        "feats_hidden/generator_eval_s*of2.npz, the cache the head was trained and "
                        "evaluated on?",
                "h_span": eq.get("fullres_tf_vs_deployed"),
                "head_logits": eq.get("head_logits_fullres_tf_vs_deployed"),
                "picks_changed_head_only":
                    v(cmpB, "head_only::fullres_tf__vs__fusion::deployed", "picks_changed"),
                "note": "this is the MATCHED IN-SESSION CONTROL the project's +-0.008 "
                        "regeneration caveat requires: every captured arm is compared against a "
                        "teacher-forced arm computed in the same session, same box, same numerics."},
            "shuffled_feature_null": B["shuffled_feature_null"],
        }),

        "DELIVERABLE_1_capture": {
            "how": "src/training_methods/free_head_capture.py drives model.generate() from the PROMPT "
                   "ONLY with a LogitsProcessor forcing the stored candidate's token ids, then reads "
                   "layer-21 hidden states out of generate()'s own per-step outputs.  That is the real "
                   "generation code path -- prefill, then one cached decode step per token -- so the "
                   "captured states are what a deployed capture would see, while the token sequence is "
                   "guaranteed to be the stored candidate rather than a fresh sample.",
            "definition_identical_to_the_trained_head":
                "same base Lingshu-7B (no adapter), same SYS_GEN answering prompt, same layer 21, "
                "same span = mean over the candidate's own tokens, same fp16 storage, same row keys. "
                "extract_generator_hidden.build_eval_rows / .encode are IMPORTED, not re-implemented.",
            "tokenisation_boundary": {
                cap: eq[f"{cap}_row_diagnostics"] for cap in ("cap320", "fullres")
                if f"{cap}_row_diagnostics" in eq},
        },

        "DELIVERABLE_2_equivalence": {
            "question": "do the captured states reproduce the teacher-forced ones, and -- the part "
                        "that matters -- do the frozen head's SCORES and ARGMAX PICKS change?",
            "h_span_deviation": {k: v_ for k, v_ in eq.items()
                                 if "row_diagnostics" not in k and "head_logits" not in k},
            "head_logit_deviation": {k: v_ for k, v_ in eq.items() if "head_logits" in k},
            "candidate_auroc": B["candidate_auroc"],
            "picks_and_endpoint": {
                "AR_vs_TF_same_resolution": {
                    k: cmpB[k] for k in cmpB
                    if "__vs__" in k and k.split("__vs__")[0].replace("_ar", "_tf") == k.split("__vs__")[1]},
                "all_comparisons": cmpB},
        },

        "DELIVERABLE_3_cost": B["cost"],

        "DELIVERABLE_4_head_only": {
            "question": "the head alone scores higher than the LoRA verifier under the judge, so "
                        "dropping the LoRA entirely might be cheaper AND better.  Tested explicitly.",
            "per_seed_head_only": A["head_per_seed"],
            "arms_on_the_deployed_features": {
                "incumbent_LoRA_alone": A["arms"]["incumbent"],
                "head_ens8_alone": A["arms"]["head_ens8"],
                "fusion": A["arms"]["fusion"],
                "self_consistency_free_control": A["arms"]["self_consistency"]},
            "head_vs_incumbent": A["comparisons"]["head_vs_incumbent"],
            "head_vs_fusion": A["comparisons"]["head_vs_fusion"],
            "fusion_vs_incumbent": A["comparisons"]["fusion_vs_incumbent"],
        },

        "vs_always_7b_the_new_baseline": {
            "deployed_features": A["vs_always_7b"],
            "captured_features": B["vs_always_7b"],
            "cells": "3 of the 8 macro cells are open-text and carry a candidate pool; the selector "
                     "does not apply to the other 5 and they are neither claimed nor charged here."},

        "arms_all_feature_sources": {k: arm(k) for k in arms},
        "baselines": A["baselines"],
    }
    json.dump(out, open(OUT, "w"), indent=1, default=float)
    print("wrote", OUT, f"({os.path.getsize(OUT)/1e3:.0f} kB)")
    return out


if __name__ == "__main__":
    main()
