#!/usr/bin/env python3
"""Render the 2026-09-28 fresh-model check into markdown, FROM its raw output.

The check ran 7 independent read-only agents (one also ran the identity-prior ridge experiment) and one
adversarial verifier per agent, told to REFUTE every problem found. Raw output of record:
artifacts/check_2026-09-28_findings.json. This script only formats it -- every figure in the rendered
doc is the agents' quoted evidence, verbatim, so it cannot drift from its source.

  python3 src/audit_2026_09_18/check_2026_09_28_report.py > results/cascade_methods/docs/current/CHECK_2026-09-28.md
"""
import json
d = json.load(open("results/cascade_methods/artifacts/check_2026-09-28_findings.json"))
ORDER = [("d3-numbers", "D3 — every number re-derived"), ("d3-method", "D3 — methodology and leakage"),
         ("d3-ridge-prior", "D3 — the identity-prior ridge experiment"), ("d3-code", "D3 — code review"),
         ("session-claims", "Numeric claims made to Leo during the session"),
         ("deck", "The 2026-09-14 professor deck"), ("project-state", "Preservation and bookkeeping")]
SEV = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
P = print
P("# Fresh-model check — 2026-09-28\n")
P("*Generated by `src/audit_2026_09_18/check_2026_09_28_report.py` from "
  "`artifacts/check_2026-09-28_findings.json`. Every finding below is the agents' output verbatim. The "
  "synthesis section is the orchestrating session's; its numbers are read from artifacts by this script.*\n")
P("Run on the switch to a new model, to re-examine this session's work rather than repeat it. Seven")
P("independent read-only checks, then one adversarial verifier per check, instructed to refute every")
P("problem by returning to the primary source. **Verdict** is the verifier's; **severity** is the")
P("verifier's re-grade. A REFUTED finding is listed so the record is complete, but is not a problem.\n")
tot = {}
rows = []
for key, title in ORDER:
    f = d["checks"].get(key) or {}
    V = {v["id"]: v for v in (d["verifs"].get(key) or {}).get("verdicts", [])}
    for x in f.get("findings", []):
        v = V.get(x["id"])
        verdict = v["verdict"] if v else ("n/a (info)" if x["status"] == "problem" else "OK")
        sev = v["severity_adjusted"] if v else x["severity"]
        rows.append((key, x, v, verdict, sev))
        tot[verdict] = tot.get(verdict, 0) + 1
ip = json.load(open("results/cascade_methods/artifacts/d3_ridge_identity_prior_2026-09-28.json"))
zp = json.load(open("results/cascade_methods/artifacts/d3_pair_efficiency_2026-09-21.json"))
c, z = ip["curve"], zp["curve"]
P("## Synthesis — read this first\n")
P("**The checks ran independently, so one overrides another.** The D3-numbers check concluded that "
  "\"the ridge map does not pay\" still holds; it did not know about the ridge-prior experiment, which "
  "refutes it. That conclusion came from shrinking the map toward zero. Shrunk toward the identity, on the "
  f"same pairs and validation splits, the map gives {c['100']['macro_mean']:+.4f} at 100 pairs (zero prior "
  f"{z['100']['macro_mean']:+.4f}) and {c['all']['macro_mean']:+.4f} at all {c['all']['n_pairs']:,} "
  f"(zero prior {z['all']['macro_mean']:+.4f}); its W = I arm reproduces arm B at "
  f"{ip['identity_arm']['macro']:+.6f} (`d3_ridge_identity_prior_2026-09-28.json`).\n")
P("**What changed as a result** (commits on `audit-2026-09-18`, 2026-09-28): the identity-prior experiment "
  "was committed; `LINEAGE_TRANSFER_2026-09-28.md` carries a supersession banner rather than a rewrite; "
  "CLAUDE.md, AUDIT_2026-09-18.md, NEW_DIRECTIONS_2026-09-20.md, TRANSFER_WALL_2026-08-21.md and the "
  "indexes were corrected. **Deliberately NOT acted on** (Leo's call, 2026-09-28): rewriting the D3 "
  "writeup, and correcting and republishing the 2026-09-14 deck — the deck findings below are the "
  "to-do list for that.\n")
P("| verdict | findings |\n|---|---:|")
for k in ("CONFIRMED", "PLAUSIBLE", "REFUTED", "n/a (info)", "OK"):
    if k in tot: P(f"| {k} | {tot[k]} |")
P("")
for key, title in ORDER:
    f = d["checks"].get(key) or {}
    P(f"\n## {title}\n")
    P(f"{f.get('summary','(no summary)')}\n")
    mine = [r for r in rows if r[0] == key and r[1]["status"] == "problem"]
    mine.sort(key=lambda r: SEV.get(r[4], 9))
    for _, x, v, verdict, sev in mine:
        P(f"### {x['id']} · {sev} · {verdict}\n")
        P(f"**Finding.** {x['claim']}\n")
        P(f"**Evidence.** {x['evidence']}\n")
        if v: P(f"**Verifier.** {v['reasoning']} — *{v['evidence']}*\n")
        if x.get("fix"): P(f"**Fix.** {x['fix']}\n")
        P(f"*Location:* `{x['location']}`\n")
    ok = [r for r in rows if r[0] == key and r[1]["status"] == "confirmed_ok"]
    if ok:
        P("**Checked and holds:**\n")
        for _, x, _, _, _ in ok: P(f"- {x['claim']}")
        P("")
