#!/usr/bin/env python3
"""D3 (b') -- IS "WORSE THAN DOING NOTHING BELOW ~3,000 PAIRS" AN ARTEFACT OF SHRINKING TOWARD ZERO?

WHY THIS FILE EXISTS.  LINEAGE_TRANSFER_2026-09-28.md (generated by d3_writeup.py from
d3_pair_efficiency_2026-09-21.json) says the Qwen2.5-VL-7B -> Lingshu-7B ridge alignment map is
"worse than doing nothing" below ~3,000 label-free pairs, and that this "is not fixable by collecting
fewer pairs".  d3_pair_efficiency.py fits an ordinary ridge,  W = argmin ||Zq W - Zl||^2 + lam ||W||^2,
whose prior is W = 0: with few pairs the map is shrunk toward ZERO, i.e. toward sending every Qwen state to
the Lingshu mean, which destroys the signal the frozen probes read.  But the two models share one
architecture (Lingshu is a fine-tune of Qwen2.5-VL-7B), and the identity map already works -- it IS arm B
(Qwen's own train-half standardiser, then the Lingshu probes), +0.0490 macro.  A ridge that shrinks toward
the IDENTITY instead should degrade gracefully to arm B at small n rather than collapse below it.

This file is a copy of d3_pair_efficiency.py with ONLY these changes:
  (a) fit_map solves the RESIDUAL ridge  Delta = argmin ||Zq Delta - (Zl - Zq)||^2 + lam ||Delta||^2
      = (G + lam I)^-1 (C - G), and returns W = I + Delta;
  (b) the lambda grid is extended with 1e6 and 1e7 so the label-free selector can shrink all the way to
      W ~ I (it also records the chosen split's val-MSE and the val-MSE of W = I on the same split, as a
      diagnostic only -- selection is unchanged: minimum val-MSE over the grid);
  (c) an explicit 'identity' arm evaluated with W = I for every layer.  That IS arm B and must reproduce
      restandardised_B = +0.0490 within 0.002, otherwise the script halts and reports the discrepancy
      instead of the curve;
  (d) the output carries this docstring, the same reference block, a vs_zero_prior block pairing each n
      with d3_pair_efficiency_2026-09-21.json's curve (same subsample seeds => same pairs, same val split),
      and a COMPLETE flag written last.
NS, SEEDS, pairing key, TRAIN-half restriction, by-image split, standardisers, bootstrap, evaluate() and the
frozen probes are identical to d3_pair_efficiency.py.  (The identity arm is evaluated first, so the global
bootstrap RNG stream is shifted relative to the zero-prior run: CIs differ slightly, point deltas do not.)

  python3 src/audit_2026_09_18/d3_ridge_identity_prior.py <out.json>

Read-only, CPU, 4 threads.
"""
import hashlib, json, os, sys, time
import numpy as np
import torch

torch.set_num_threads(4)
ROOT = "/home/jamesyang/medvlthinker-imgdiff-compute"
WT = f"{ROOT}/.claude/worktrees/audit-2026-09-18"
sys.path.insert(0, os.path.join(ROOT, "src/training_methods"))
import head_sweep as HS                      # noqa: E402
from genframe_data import rank_avg           # noqa: E402
FE, CK = f"{ROOT}/feats_hidden", f"{ROOT}/ckpts/openvqa/cheap_lingshu7b"
PD = f"{ROOT}/ckpts/train/genframe_head_pooled_ens_v2"
ART = f"{ROOT}/results/cascade_methods/artifacts"
ZP = f"{WT}/results/cascade_methods/artifacts/d3_pair_efficiency_2026-09-21.json"   # the zero-prior curve
BENCH = ["pathvqa_open", "slake_open", "vqa_rad_open", "radimagenet_open",
         "kvasir_x1_open", "omnimed_open", "vqamed_open", "gemex_open"]
SHARED = {"slake_open", "vqa_rad_open"}
ENS = [18, 20, 22]
NS = [100, 300, 1000, 3000, 0]               # 0 = all available pairs (the pilot's 9,688)
SEEDS = [0, 1, 2]                            # subsample seeds, so small n carries its own spread
LAMS = (1e0, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7)   # CHANGE (b): + 1e6, 1e7
rng = np.random.default_rng(20260921); NB = 10000


def half(img):
    return int(hashlib.md5(("nd" + str(img)).encode()).hexdigest(), 16) % 2


def load(stem, dsf=None):
    z = np.load(f"{FE}/{stem}.npz"); m = json.load(open(f"{FE}/{stem}.meta.json"))
    lay = [int(x) for x in z["layers"]]
    keep = [i for i, r in enumerate(m["rows"]) if r.get("n_tok", -1) > 0 and (dsf is None or r.get("ds") in dsf)]
    H = z["h_span"]
    return {L: H[keep, lay.index(L)].astype(np.float32) for L in ENS}, [m["rows"][i] for i in keep]


def key(s):
    return " ".join(str(s).lower().split()).rstrip(".!?, ")


def boot(res, a, b):
    ks = {}
    for r in res:
        ks.setdefault(r[0], []).append(r[a] - r[b])
    s = np.array([sum(v) for v in ks.values()], float); n = np.array([len(v) for v in ks.values()], float)
    ix = rng.integers(0, len(s), size=(NB, len(s))); bb = s[ix].sum(1) / n[ix].sum(1)
    return float(s.sum() / n.sum()), [float(np.quantile(bb, .025)), float(np.quantile(bb, .975))]


t0 = time.time()
H = {}
for L in ENS:
    st = np.load(f"{PD}/standardizer_L{L}.npz"); ms = []
    for s in range(8):
        m = HS.MLP(3584, 256, 1, 0.0, False)
        m.load_state_dict(torch.load(f"{PD}/head_L{L}_seed{s}.pt", map_location="cpu")); m.eval(); ms.append(m)
    H[L] = (st["mu"].astype(np.float32), st["sd"].astype(np.float32), ms)

pairs = {L: ([], []) for L in ENS}; qtr = {L: [] for L in ENS}; held = {}
for cell in BENCH:
    Xl, rl = load("generator_eval_finelayer" if cell in SHARED else f"generator_eval_finelayer_{cell}",
                  {cell} if cell in SHARED else None)
    Xq, rq = load(f"generator_eval_qwen_{cell}")
    il = {(r["idx"], key(r["na"])): i for i, r in enumerate(rl) if half(r["img_md5"]) == 1}
    iq = [(i, il[(r["idx"], key(r["na"]))]) for i, r in enumerate(rq)
          if half(r["img_md5"]) == 1 and (r["idx"], key(r["na"])) in il]
    trq = np.array([half(r["img_md5"]) == 1 for r in rq])
    for L in ENS:
        if iq:
            pairs[L][0].append(Xq[L][[a for a, _ in iq]]); pairs[L][1].append(Xl[L][[b for _, b in iq]])
        qtr[L].append(Xq[L][trq])
    g = {}
    for l in open(f"{CK}/ckpt_{cell}_qwen25vl7b.judge.jsonl"):
        if l.strip():
            d = json.loads(l); g[d["idx"]] = int(d["judge_ok"])
    held[cell] = ({L: Xq[L][~trq] for L in ENS}, [rq[i] for i in np.where(~trq)[0]], g)
    print(f"{cell:17} paired rows {len(iq):6} ({time.time()-t0:.0f}s)", flush=True)
    del Xl, Xq

PAIRQ = {L: np.concatenate(pairs[L][0]) for L in ENS}
PAIRL = {L: np.concatenate(pairs[L][1]) for L in ENS}
STQ = {}
for L in ENS:
    allq = np.concatenate(qtr[L]); STQ[L] = (allq.mean(0), allq.std(0) + 1e-6)
NTOT = len(PAIRQ[ENS[0]])
print(f"\n{NTOT:,} label-free pairs available in total\n", flush=True)


def fit_map(L, idx, seed):
    """CHANGE (a): residual ridge  Delta = argmin ||Zq Delta - (Zl - Zq)||^2 + lam ||Delta||^2,  W = I + Delta.
    Same pairs, same 10% label-free val split, same val-MSE selection as d3_pair_efficiency.fit_map."""
    muq, sdq = STQ[L]; mul, sdl, _ = H[L]
    Zq = (PAIRQ[L][idx] - muq) / sdq
    Zl = (PAIRL[L][idx] - mul) / sdl
    r = np.random.default_rng(1000 + seed)
    perm = r.permutation(len(Zq)); k = max(1, len(Zq) // 10); va, tr = perm[:k], perm[k:]
    G = (Zq[tr].T @ Zq[tr]).astype(np.float64); C = (Zq[tr].T @ Zl[tr]).astype(np.float64)
    RHS = C - G                                  # = Zq_tr^T (Zl_tr - Zq_tr)
    I = np.eye(G.shape[0])
    base = float(((Zq[va] - Zl[va]) ** 2).mean())   # val-MSE of W = I on this split (diagnostic only)
    best = None
    for lam in LAMS:
        w = (I + np.linalg.solve(G + lam * I, RHS)).astype(np.float32)
        err = float(((Zq[va] @ w - Zl[va]) ** 2).mean())
        if best is None or err < best[1]:
            best = (lam, err, w)
    return best + (base,)


def evaluate(W):
    """Macro verifier-minus-greedy over the eight held-out halves, with the mapped Qwen states."""
    per = {}
    for cell in BENCH:
        X, rows, g = held[cell]
        y = np.array([r["y"] for r in rows], int)
        byq = {}
        for i, r in enumerate(rows):
            byq.setdefault(r["idx"], []).append(i)
        sc = []
        for L in ENS:
            muq, sdq = STQ[L]; _, _, ms = H[L]
            Z = ((X[L] - muq) / sdq) @ W[L]
            sc.append(np.stack([HS.predict(m, Z.astype(np.float32)) for m in ms]))
        res = []
        for q, ii in byq.items():
            if q not in g:
                continue
            ii = np.array(ii)
            hr = np.mean([rank_avg(s[k][ii]) for s in sc for k in range(s.shape[0])], axis=0)
            res.append([rows[ii[0]]["img_md5"], g[q], int(y[ii][int(np.argmax(hr))])])
        d, ci = boot(res, 2, 1)
        per[cell] = {"n": len(res), "delta": d, "ci": ci}
    per["_macro"] = float(np.mean([v["delta"] for k, v in per.items() if not k.startswith("_")]))
    return per


out = {"title": "D3(b'): ridge alignment map shrunk toward the IDENTITY instead of zero -- does it floor at arm B?",
       "date": "2026-09-28", "docstring": __doc__, "no_fabricated_numbers": True,
       "currency": "judge of record (MedVLThinker-32B)",
       "pairs_available": int(NTOT), "seeds": SEEDS, "bootstrap": f"{NB}, clustered by img_md5",
       "lambda_grid": list(LAMS), "prior": "W = I + Delta, ridge penalty on Delta (residual ridge)",
       "threads": {k: os.environ.get(k) for k in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS")}
                  | {"torch": torch.get_num_threads()},
       "reference": {"zero_shot_A": 0.0451, "restandardised_B": 0.0490,
                     "ridge_all_pairs_pilot": 0.0603, "qwen_native": 0.0820,
                     "source": "pilot_lineage_alignment_2026-09-20.json"},
       "identity_arm": {}, "curve": {}, "COMPLETE": False}

# CHANGE (c): the identity arm, W = I for every layer.  This is arm B by construction.
per = evaluate({L: np.eye(3584, dtype=np.float32) for L in ENS})
idm = per["_macro"]; dev = idm - out["reference"]["restandardised_B"]
out["identity_arm"] = {"macro": idm, "vs_restandardised_B": out["reference"]["restandardised_B"],
                       "deviation": dev, "tolerance": 0.002, "ok": bool(abs(dev) <= 0.002),
                       "per_benchmark": {k: v for k, v in per.items() if not k.startswith("_")}}
print(f"identity arm (W = I, = arm B)  macro {idm:+.4f}  vs B {out['reference']['restandardised_B']:+.4f}"
      f"  deviation {dev:+.5f}   ({time.time()-t0:.0f}s)", flush=True)
json.dump(out, open(sys.argv[1], "w"), indent=1)
if not out["identity_arm"]["ok"]:
    out["HALTED"] = (f"identity arm {idm:+.5f} deviates from restandardised_B "
                     f"{out['reference']['restandardised_B']:+.4f} by {dev:+.5f} > 0.002; curve NOT run")
    json.dump(out, open(sys.argv[1], "w"), indent=1)
    print(out["HALTED"], flush=True)
    sys.exit(2)

for n in NS:
    lab = "all" if n == 0 else str(n)
    macros = []; lams = {}; vmse = {}; vmse_id = {}
    for seed in (SEEDS if n else [0]):          # the full-pair point has nothing to subsample
        r = np.random.default_rng(7000 + seed)
        idx = np.arange(NTOT) if n == 0 else r.choice(NTOT, size=min(n, NTOT), replace=False)
        W = {}
        for L in ENS:
            lam, err, w, base = fit_map(L, idx, seed)
            W[L] = w; lams.setdefault(str(L), []).append(lam)
            vmse.setdefault(str(L), []).append(err); vmse_id.setdefault(str(L), []).append(base)
        per = evaluate(W)
        macros.append(per["_macro"])
        if seed == (SEEDS[0] if n else 0):
            first = per
    out["curve"][lab] = {"n_pairs": int(NTOT if n == 0 else min(n, NTOT)),
                         "macro_mean": float(np.mean(macros)),
                         "macro_sd": float(np.std(macros, ddof=1)) if len(macros) > 1 else 0.0,
                         "macro_per_seed": [float(x) for x in macros],
                         "ridge_lambda": lams,
                         "val_mse_chosen": vmse, "val_mse_identity_same_split": vmse_id,
                         "per_benchmark_first_seed": {k: v for k, v in first.items() if not k.startswith("_")}}
    print(f"n_pairs {lab:>5}  macro {np.mean(macros):+.4f}"
          f"{'  sd %.4f' % np.std(macros, ddof=1) if len(macros) > 1 else ''}"
          f"   lambdas {lams}   ({time.time()-t0:.0f}s)", flush=True)
    json.dump(out, open(sys.argv[1], "w"), indent=1)

# CHANGE (d): pair each n with the zero-prior curve (same subsample seeds => same pairs and val split).
zp = json.load(open(ZP))
out["vs_zero_prior"] = {"source": "d3_pair_efficiency_2026-09-21.json", "rows": {}}
for lab, v in out["curve"].items():
    z = zp["curve"][lab]
    out["vs_zero_prior"]["rows"][lab] = {
        "n_pairs": v["n_pairs"],
        "zero_prior_macro_mean": z["macro_mean"], "zero_prior_macro_sd": z["macro_sd"],
        "zero_prior_per_seed": z["macro_per_seed"], "zero_prior_lambda": z["ridge_lambda"],
        "identity_prior_macro_mean": v["macro_mean"], "identity_prior_macro_sd": v["macro_sd"],
        "identity_prior_per_seed": v["macro_per_seed"], "identity_prior_lambda": v["ridge_lambda"],
        "identity_minus_zero_prior": v["macro_mean"] - z["macro_mean"],
        "identity_minus_zero_prior_per_seed": [a - b for a, b in zip(v["macro_per_seed"], z["macro_per_seed"])],
        "identity_prior_minus_identity_arm": v["macro_mean"] - idm,
        "zero_prior_minus_identity_arm": z["macro_mean"] - idm}
out["VERDICT"] = (
    f"Identity arm (W = I, arm B) {idm:+.4f} (reference B +0.0490). Identity-prior curve: " +
    ", ".join(f"{k}={v['macro_mean']:+.4f}" for k, v in out["curve"].items()) +
    ". Zero-prior curve (d3_pair_efficiency_2026-09-21.json): " +
    ", ".join(f"{k}={v['macro_mean']:+.4f}" for k, v in zp["curve"].items()) + ".")
out["seconds"] = round(time.time() - t0, 1)
out["COMPLETE"] = True
json.dump(out, open(sys.argv[1], "w"), indent=1)
print("\n" + out["VERDICT"])
