#!/usr/bin/env python3
"""
bestofn_measure_vllm.py -- measure best-of-8 cost on the serving stack we ACTUALLY generate with.

WHY THIS EXISTS.  bestofn_latency_energy_2026-08-03.json measured best-of-8 under HUGGINGFACE with
`num_return_sequences=8`.  HF's GenerationMixin._expand_inputs_for_generation "expands tensors from
[batch_size, ...] to [batch_size * expand_size, ...]" -- it repeat_interleaves the input, so the
prompt AND the image are encoded EIGHT TIMES.  Under that configuration the as-charged 8.00x
FLOP-equivalent figure is correct, and the measured 2.95x energy / 1.99x latency are batching
efficiency at CONSTANT arithmetic.

But every candidate-set pool in this project was generated by src/labeling/run_openvqa.py, which
uses vLLM with `SamplingParams(..., n=A.n_samples, ...)`.  vLLM forks the n sequences AFTER a single
shared prefill: the prompt is encoded ONCE.  On the measured token geometry
(prompt 322.7 tokens, 6.0 generated per sample) that is

    HF repeat-8         8 x (322.7 + 6.0) = 2629.6 forward-tokens   8.00x a greedy answer
    vLLM shared prefill     322.7 + 8x6.0 =  370.7 forward-tokens   1.13x a greedy answer

a 7.1x difference, because the workload is 82.1% LM prefill / 16.7% vision tower / 1.2% decode
(shared_prefix_verifier_2026-08-16.json) -- the prompt and image are ~99% of the work, so sharing
them removes almost all of it.  THE DEPLOYED PATH HAS NEVER BEEN MEASURED.  This measures it.

WHAT IS AND IS NOT MEASURED HERE.
  MEASURED:  gen1 (n=1, greedy) and gen8 (n=8, T=0.7) under vLLM, one request at a time, NVML power
             integrated over the timed call across visible GPUs, warmup discarded.  The probe adds
             ~0.001 FLOP-eq and is not timed; its cost is a CPU matmul on states already in hand.
  NOT MEASURED:  the July LoRA verifier arm.  CLAUDE.md section 0: vLLM 0.9.0.1 silently drops all
             192 visual.* LoRA modules (same adapter 0.775204 HF vs 0.702997 vLLM).  Never score a
             visual LoRA under vLLM.  The LoRA arm stays on the HF numbers and the asymmetry is
             recorded in the artifact rather than papered over.

CONTROLS.
  * enable_prefix_caching=False.  vLLM can also cache prefixes ACROSS requests; every question here
    has a different image so that would not fire, but leaving it on would make the measurement
    depend on request order.  We want the WITHIN-request n-way sharing only.
  * One request in flight at a time, so continuous batching cannot silently overlap items.
  * Same item selection, same cap320 geometry, same warmup discipline as the HF harness, so the
    gen1 row is directly comparable to that run's gen1 (360.4 ms / 55.89 J).

  CUDA_VISIBLE_DEVICES=0 python3 src/cascade_methods/bestofn_measure_vllm.py \
      --model_path <lingshu-7b snapshot> --n 20 --warmup 3 \
      --out results/cascade_methods/artifacts/bestofn_vllm_2026-09-16.json
"""
import argparse, os, io, glob, time, json, threading
import numpy as np
import pynvml
from PIL import Image

ap = argparse.ArgumentParser()
ap.add_argument("--model_path", required=True)
ap.add_argument("--n", type=int, default=20, help="items KEPT after warmup")
ap.add_argument("--warmup", type=int, default=3)
ap.add_argument("--k", type=int, default=8)
ap.add_argument("--temp", type=float, default=0.7)
ap.add_argument("--max_new", type=int, default=32)
ap.add_argument("--gpu_mem", type=float, default=0.88)
ap.add_argument("--max_model_len", type=int, default=4096)
ap.add_argument("--out", required=True)
A = ap.parse_args()

MAXPX, MIN_PX = 1280 * 28 * 28 // 4, 4 * 28 * 28          # cap320, identical to run_openvqa.py
SYS = ("You are an expert medical image analyst. Answer the question with a short, specific phrase. "
       "Do not explain.")

# ---------------- NVML, verbatim from bestofn_measure_batch8.py so energy is comparable ----------
pynvml.nvmlInit()
_vis = os.environ.get("CUDA_VISIBLE_DEVICES", "").strip()
_toks = [x.strip() for x in _vis.split(",") if x.strip() != ""]
_idxs = [int(t) for t in _toks] if (_toks and all(t.isdigit() for t in _toks)) \
        else list(range(pynvml.nvmlDeviceGetCount()))
HS = [pynvml.nvmlDeviceGetHandleByIndex(i) for i in _idxs]
NG = len(HS)
GPU_NAMES = [pynvml.nvmlDeviceGetName(h) for h in HS]
GPU_NAMES = [g.decode() if isinstance(g, bytes) else g for g in GPU_NAMES]
GPU_LIMIT_W = [pynvml.nvmlDeviceGetEnforcedPowerLimit(h) / 1000.0 for h in HS]
_W_LAST = [0.0]


def watts():
    try:
        w = sum(pynvml.nvmlDeviceGetPowerUsage(h) for h in HS) / 1000.0
        _W_LAST[0] = w
        return w
    except pynvml.NVMLError:
        return _W_LAST[0]


class E:
    """Integrate W over the timed call (10 ms sampling)."""
    def __init__(s): s.go = False; s.j = 0.0
    def __enter__(s):
        s.j = 0.0; s.go = True
        def loop():
            last = time.time()
            while s.go:
                time.sleep(0.01); now = time.time(); s.j += watts() * (now - last); last = now
        s.th = threading.Thread(target=loop); s.th.start(); return s
    def __exit__(s, *a): s.go = False; s.th.join()


def idle_watts(sec=3.0):
    t0 = time.time(); acc = 0.0; last = t0
    while time.time() - t0 < sec:
        time.sleep(0.02); now = time.time(); acc += watts() * (now - last); last = now
    return acc / (last - t0)


def timed(fn):
    """No torch.cuda.synchronize(): vLLM's engine runs out of process and llm.generate() already
    blocks until every sequence in the request has finished."""
    with E() as e:
        t0 = time.time(); out = fn(); dt = time.time() - t0
    return dt, e.j, out


# ---------------- the same real vqa_rad open items, same selection rule --------------------------
import pandas as pd
df = pd.concat([pd.read_parquet(f) for f in sorted(glob.glob("/data/dan/dataset/vqa_rad/data/test-*.parquet"))],
               ignore_index=True)
items = []
for _, r in df.iterrows():
    q = r.get("question"); a = r.get("answer")
    if q is None and "conversations" in r:
        conv = r["conversations"]; q = conv[0]["value"].replace("<image>", "").strip(); a = conv[1]["value"]
    if str(a).strip().lower() in ("yes", "no"):
        continue
    img = r["image"]
    if isinstance(img, dict) and "bytes" in img:
        items.append((str(q), Image.open(io.BytesIO(img["bytes"])).convert("RGB"), str(a)))
    if len(items) >= A.n + A.warmup:
        break
print(f"{len(items)} items, K={A.k}, visible GPUs={NG} {GPU_NAMES} limit={GPU_LIMIT_W} W", flush=True)

from transformers import AutoProcessor
from qwen_vl_utils import process_vision_info
from vllm import LLM, SamplingParams

proc = AutoProcessor.from_pretrained(A.model_path, trust_remote_code=True)


def build(q, img):
    """Byte-identical prompt construction to run_openvqa.py:build()."""
    im = [{"type": "image", "image": img, "max_pixels": MAXPX, "min_pixels": MIN_PX}]
    msgs = [{"role": "system", "content": SYS},
            {"role": "user", "content": im + [{"type": "text", "text": q}]}]
    text = proc.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
    imgs, _ = process_vision_info(msgs)
    req = {"prompt": text}
    if imgs:
        req["multi_modal_data"] = {"image": imgs}
    return req


llm = LLM(model=A.model_path, tensor_parallel_size=1, dtype="bfloat16",
          gpu_memory_utilization=A.gpu_mem, max_model_len=A.max_model_len,
          limit_mm_per_prompt={"image": 4}, trust_remote_code=True,
          enable_prefix_caching=False)                       # see CONTROLS in the docstring

SP1 = SamplingParams(temperature=0.0, max_tokens=A.max_new, n=1)
SP8 = SamplingParams(temperature=A.temp, max_tokens=A.max_new, n=A.k)

REC = {k: [] for k in ("gen1", "gen8")}
TOK = {k: {"prompt": [], "gen_total": []} for k in ("gen1", "gen8")}

W_IDLE = idle_watts(3.0)
print(f"idle draw over visible GPUs (model resident): {W_IDLE:.1f} W", flush=True)

for i, (q, img, gold) in enumerate(items):
    keep = i >= A.warmup
    req = build(q, img)

    dt1, j1, o1 = timed(lambda: llm.generate([req], SP1, use_tqdm=False))
    dt8, j8, o8 = timed(lambda: llm.generate([req], SP8, use_tqdm=False))

    if not keep:
        continue
    REC["gen1"].append((dt1 * 1000.0, j1))
    REC["gen8"].append((dt8 * 1000.0, j8))
    TOK["gen1"]["prompt"].append(len(o1[0].prompt_token_ids))
    TOK["gen1"]["gen_total"].append(sum(len(c.token_ids) for c in o1[0].outputs))
    TOK["gen8"]["prompt"].append(len(o8[0].prompt_token_ids))
    TOK["gen8"]["gen_total"].append(sum(len(c.token_ids) for c in o8[0].outputs))
    print(f"  [{len(REC['gen1']):2d}/{A.n}] gen1 {dt1*1000:7.1f} ms {j1:6.2f} J | "
          f"gen8 {dt8*1000:7.1f} ms {j8:6.2f} J | ratio {dt8/dt1:.2f}x lat {j8/j1:.2f}x J", flush=True)
    if len(REC["gen1"]) >= A.n:
        break


def stat(v):
    a = np.array(v, dtype=float)
    return {"n": len(a), "mean": round(float(a.mean()), 2), "median": round(float(np.median(a)), 2),
            "sd": round(float(a.std(ddof=1)), 2) if len(a) > 1 else 0.0}


art = {"title": "Best-of-8 cost on the vLLM serving path (shared prefill), the stack the pools were generated with",
       "date": "2026-09-16", "no_fabricated_numbers": True,
       "harness": ("vLLM, ONE request in flight, enable_prefix_caching=False, cap320 "
                   "(max_pixels=1280*28*28//4), real vqa_rad open items, NVML power integrated over "
                   "the timed call across visible GPUs, warmup discarded. Prompt construction is "
                   "byte-identical to src/labeling/run_openvqa.py:build()."),
       "why": ("bestofn_latency_energy_2026-08-03.json measured HF num_return_sequences=8, which "
               "repeat_interleaves the input and therefore encodes the prompt and image EIGHT "
               "times. Every candidate-set pool in this project was generated under vLLM with n=8, "
               "which forks after ONE shared prefill. This measures the path we actually use."),
       "NOT_measured": ("the July LoRA verifier arm. vLLM 0.9.0.1 silently drops all 192 visual.* "
                        "LoRA modules (CLAUDE.md section 0), so a LoRA number from this harness "
                        "would be wrong. That arm keeps its HF figures and the comparison across "
                        "the two rows is therefore across two serving stacks -- stated, not hidden."),
       "model": A.model_path, "k": A.k, "temperature": A.temp, "max_new": A.max_new,
       "gpus": GPU_NAMES, "power_limit_w": GPU_LIMIT_W, "idle_w_model_resident": round(W_IDLE, 1),
       "n_kept": len(REC["gen1"]), "warmup": A.warmup,
       "measured": {}, "tokens": {}}

for k in ("gen1", "gen8"):
    art["measured"][k] = {"lat_ms": stat([r[0] for r in REC[k]]), "energy_j": stat([r[1] for r in REC[k]])}
    art["tokens"][k] = {"prompt_mean": round(float(np.mean(TOK[k]["prompt"])), 1),
                        "generated_total_mean": round(float(np.mean(TOK[k]["gen_total"])), 1)}

g1l = art["measured"]["gen1"]["lat_ms"]["mean"]; g8l = art["measured"]["gen8"]["lat_ms"]["mean"]
g1j = art["measured"]["gen1"]["energy_j"]["mean"]; g8j = art["measured"]["gen8"]["energy_j"]["mean"]
P = art["tokens"]["gen8"]["prompt_mean"]; G8 = art["tokens"]["gen8"]["generated_total_mean"]
G1 = art["tokens"]["gen1"]["generated_total_mean"]
art["ratios_vs_greedy"] = {"latency": round(g8l / g1l, 3), "energy": round(g8j / g1j, 3)}
art["forward_tokens_per_question"] = {
    "greedy": round(P + G1, 1),
    "vllm_shared_prefill_bo8": round(P + G8, 1),
    "hf_repeat8_bo8": round(A.k * (P + G8 / A.k), 1),
    "flopeq_shared": round((P + G8) / (P + G1), 3),
    "flopeq_as_charged": float(A.k),
    "note": ("forward-tokens is a proxy for FLOPs in a dense transformer (~2*params*tokens). "
             "flopeq_shared is what vLLM's within-request n-way fork actually costs; "
             "flopeq_as_charged is the HF repeat-8 convention the 2026-08-03 artifact used."),
}
art["HF_COMPARISON"] = {
    "source": "bestofn_latency_energy_2026-08-03.json (HF num_return_sequences=8)",
    "hf_gen1_lat_ms": 360.4, "hf_gen1_energy_j": 55.89,
    "hf_gen8_lat_ms": 716.8, "hf_gen8_energy_j": 165.09,
    "hf_ratio_latency": 1.99, "hf_ratio_energy": 2.95,
}
tmp = A.out + ".tmp"
with open(tmp, "w") as f:
    json.dump(art, f, indent=1)
os.replace(tmp, A.out)
print(f"\ngen1 {g1l:.1f} ms {g1j:.2f} J  |  gen8 {g8l:.1f} ms {g8j:.2f} J")
print(f"vLLM best-of-8 vs greedy: {g8l/g1l:.2f}x latency, {g8j/g1j:.2f}x energy")
print(f"  (HF repeat-8 measured 1.99x / 2.95x -- see HF_COMPARISON)")
print(f"forward-tokens: greedy {P+G1:.1f} | vLLM shared {P+G8:.1f} ({(P+G8)/(P+G1):.2f}x) | "
      f"HF as-charged {A.k*(P+G8/A.k):.1f} ({A.k:.2f}x)")
print(f"DONE wrote {A.out}")
