#!/usr/bin/env python3
"""
gen_slake_open_bestofN.py -- FILL the one missing open-text best-of-N verifier dump: SLAKE-open.

CONTEXT. integrated_method.py's open-text arm uses the accuracy-winning piece "7B best-of-8 + trained
verifier SELECTION (lora_verifier_pooled4)". Every open cell has a transfer_dump_<ds>_lingshu7b.json
in ckpts/train/lora_verifier_pooled4/ EXCEPT slake_open -> open_slake() falls back to 7B greedy +
seqlogprob (leaving the best-of-N win unrealized on SLAKE). This script produces that missing dump.

MIRRORS the sibling dumps EXACTLY. All other transfer_dump_*_lingshu7b.json were written by
src/training_methods/verifier_transfer_eval.py: reuse the EXISTING K=8 temperature samples
(ckpts/openvqa/cheap_lingshu7b/ckpt_slake_open_lingshu7b_sc8.jsonl, generated by run_openvqa.py
--n_samples 8 --temp 0.7 --cap cap320, same as the other datasets) and their per-candidate judge
labels (ckpt_..._sc8_scexploded.judge.jsonl -> `sl`), and run the pooled4 verifier (Lingshu-7B base +
LoRA) POINTWISE over the 8 candidates -> `scores`. Verifier formula = pyes() from verifier_transfer_eval.py
verbatim (py/(py+pn) over the single 'Yes'/'No' next-token logits, image at fullres MAXPX=1280*28*28).
Only NEW compute vs the sibling dumps: the pooled4-verifier forward passes (never run for slake_open).

MEMORY-SAFE: single Lingshu-7B (+LoRA) on GPU0, tp=1, batch=1 forward, bf16, no_grad. RESUMABLE:
per-question ckpt jsonl; re-running skips done idx. SELF-GUARDED: wrap the launch in
`timeout 3600 ... || retry` (see runner at bottom of this docstring).

OUTPUTS (same schema as the sibling transfer dumps: {ds,idx,sl[8],scores[8],pick,greedy_ok,preds[8]}):
  - ckpts/train/lora_verifier_pooled4/transfer_dump_slake_open_lingshu7b.json   (so integrated_method
    picks it up and stops falling back to greedy)
  - ckpts/openvqa/ckpt_slake_open_lingshu7b_bestofN_verified.jsonl              (per-question jsonl)
  - results/cascade_methods/artifacts/slake_open_bestofN.json                   (dump + summary numbers)

Launch (from repo root):
  HF_HOME=/data/dan/hf_cache CUDA_VISIBLE_DEVICES=0 python3 src/cascade_methods/gen_slake_open_bestofN.py
"""
import os, json, math, argparse
import numpy as np
from collections import defaultdict, Counter

ROOT = os.path.expanduser("~/medvlthinker-imgdiff-compute")
J = lambda p: os.path.join(ROOT, p)
CK = "ckpts/openvqa/cheap_lingshu7b"
ADAPTER = "ckpts/train/lora_verifier_pooled4"
TAG = "lingshu7b"
DS = "slake_open"
MAXPX, MINPX = 1280 * 28 * 28, 4 * 28 * 28   # verifier resolution == verifier_transfer_eval.py (fullres)
# grader system prompt: verbatim from verifier_transfer_eval.py / run_mcq_generate_verify.py
SYS = ("You are a careful medical exam grader. Given a question and a proposed answer, decide whether the "
       "proposed answer is correct. Respond with only 'Yes' or 'No'.")


def norm(s):
    return str(s).strip().lower()


def loadj(p):
    return [json.loads(l) for l in open(p) if l.strip()] if os.path.exists(p) else []


def load_slake_items():
    """qid -> (question, gold, img_path). Mirrors run_openvqa.py's slake_open loader EXACTLY."""
    d = json.load(open("/data/dan/dataset/slake/test.json"))
    root = "/data/dan/dataset/slake/imgs"
    m = {}
    for x in d:
        if x.get("answer_type") != "OPEN" or x.get("q_lang") != "en":
            continue
        ip = os.path.join(root, x["img_name"])
        if os.path.exists(ip):
            m[x["qid"]] = (x["question"], str(x["answer"]), ip)
    return m


def build_sl_map():
    """aj[origidx][norm_answer] = judge_ok, from the exploded per-candidate judge file (verbatim mapping
    from verifier_transfer_eval.py)."""
    exp = {r["idx"]: r for r in loadj(J(f"{CK}/ckpt_{DS}_{TAG}_sc8_scexploded.jsonl"))}
    jud = {r["idx"]: int(r["judge_ok"]) for r in loadj(J(f"{CK}/ckpt_{DS}_{TAG}_sc8_scexploded.judge.jsonl"))}
    aj = defaultdict(dict)
    for cid, r in exp.items():
        if cid in jud:
            oi = cid.split("#")[0]
            oi = int(oi) if oi.lstrip("-").isdigit() else oi
            aj[oi][norm(r["modal_pred"])] = jud[cid]
    return aj


def score_dump(A):
    import torch
    from transformers import AutoProcessor, AutoModelForImageTextToText
    from qwen_vl_utils import process_vision_info
    from peft import PeftModel

    sc8 = loadj(J(f"{CK}/ckpt_{DS}_{TAG}_sc8.jsonl"))
    aj = build_sl_map()
    items = load_slake_items()
    print(f"[load] sc8 questions={len(sc8)}  judged-questions={len(aj)}  slake items={len(items)}", flush=True)

    proc = AutoProcessor.from_pretrained(A.model_path, trust_remote_code=True)
    YES = proc.tokenizer.encode("Yes", add_special_tokens=False)[0]
    NO = proc.tokenizer.encode("No", add_special_tokens=False)[0]
    print("[load] base Lingshu-7B + pooled4 LoRA ...", flush=True)
    model = AutoModelForImageTextToText.from_pretrained(
        A.model_path, torch_dtype=torch.bfloat16, attn_implementation="flash_attention_2").to("cuda")
    model = PeftModel.from_pretrained(model, J(ADAPTER))
    model.eval()

    def pyes(q, img, ans):
        msgs = [{"role": "system", "content": SYS},
                {"role": "user", "content": [
                    {"type": "image", "image": img, "max_pixels": MAXPX, "min_pixels": MINPX},
                    {"type": "text",
                     "text": f"Question: {q}\nProposed answer: {ans}\nIs the proposed answer correct? Answer Yes or No."}]}]
        text = proc.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        igs, vids = process_vision_info(msgs)
        enc = proc(text=[text], images=igs, videos=vids, return_tensors="pt", padding=True).to("cuda")
        with torch.no_grad():
            lg = model(**enc).logits[0, -1]
            py = math.exp(lg[YES].item()); pn = math.exp(lg[NO].item())
        return py / (py + pn) if (py + pn) > 0 else 0.5

    ckpt = J(f"{CK}/ckpt_{DS}_{TAG}_bestofN_verified.jsonl")
    done = set()
    if os.path.exists(ckpt):
        for l in open(ckpt):
            if l.strip():
                try: done.add(json.loads(l)["idx"])
                except Exception: pass
    todo = [r for r in sc8 if r["idx"] not in done and r["idx"] in aj and r["idx"] in items]
    print(f"[run] {len(done)} done, {len(todo)} to score -> {ckpt}", flush=True)

    with open(ckpt, "a") as fh:
        for n, r in enumerate(todo, 1):
            i = r["idx"]; preds = r["preds"]
            q, gold, ip = items[i]
            sl = [aj[i].get(norm(a)) for a in preds]
            if all(x is None for x in sl):
                continue
            scores = [round(float(pyes(q, ip, a)), 5) for a in preds]
            pick = int(np.argmax(scores))
            modal_norm = Counter(norm(a) for a in preds).most_common(1)[0][0]
            greedy_ok = int(aj[i].get(modal_norm, 0))
            rec = {"ds": DS, "idx": i,
                   "sl": [(-1 if x is None else int(x)) for x in sl],
                   "scores": scores, "pick": pick, "greedy_ok": greedy_ok, "preds": preds}
            fh.write(json.dumps(rec) + "\n"); fh.flush()
            if n % 50 == 0 or n == len(todo):
                print(f"   [{n}/{len(todo)}]", flush=True)
    print("[run] scoring done", flush=True)
    return ckpt


def assemble_and_report(ckpt):
    dump = loadj(ckpt)
    # keep only questions with >=1 judged candidate (mirror verifier_transfer_eval filtering)
    dump = [r for r in dump if not all(x in (None, -1) for x in r["sl"])]
    dump.sort(key=lambda r: (isinstance(r["idx"], str), r["idx"]))

    # write the canonical transfer dump (integrated_method reads THIS path) + the results artifact
    tpath = J(f"{ADAPTER}/transfer_dump_{DS}_{TAG}.json")
    json.dump(dump, open(tpath, "w"))

    def acc(f):
        return float(np.mean([f(r) for r in dump]))
    bo8 = acc(lambda r: r["sl"][int(np.argmax(r["scores"]))])           # verifier best-of-8 selection
    sl1 = acc(lambda r: 0 if r["sl"][0] in (None, -1) else int(r["sl"][0]))  # first-sample
    greedy_modal = acc(lambda r: int(r["greedy_ok"]))                    # self-consistency modal (dump greedy_ok)
    oracle = acc(lambda r: max(0 if x in (None, -1) else int(x) for x in r["sl"]))
    # external references (real, from existing judged dumps)
    cj = {r["idx"]: int(r["judge_ok"]) for r in loadj(J(f"{CK}/ckpt_{DS}_{TAG}.judge.jsonl"))}
    sj = {r["idx"]: int(r["judge_ok"]) for r in loadj(J("ckpts/openvqa/strong_lingshu/ckpt_slake_open_lingshu32b.judge.jsonl"))}
    greedy_t0 = float(np.mean(list(cj.values()))) if cj else None       # the current fallback cheap leg
    acc32nt = float(np.mean(list(sj.values()))) if sj else None         # strong leg

    summary = dict(
        dataset=DS, tag=TAG, adapter=ADAPTER, n=len(dump),
        verifier_best_of_8=round(bo8, 4),
        first_sample=round(sl1, 4),
        self_consistency_modal=round(greedy_modal, 4),
        oracle_at_8=round(oracle, 4),
        greedy_t0_judged=(round(greedy_t0, 4) if greedy_t0 is not None else None),
        acc_32b_nothink_judged=(round(acc32nt, 4) if acc32nt is not None else None),
        d_bo8_vs_greedy_t0=(round(bo8 - greedy_t0, 4) if greedy_t0 is not None else None),
        d_bo8_vs_greedy_modal=round(bo8 - greedy_modal, 4),
        d_bo8_vs_32b_nothink=(round(bo8 - acc32nt, 4) if acc32nt is not None else None),
        note=("SLAKE-open is IN-DOMAIN for pooled4 (verifier trained on slake+pathvqa+kvasir+vqa_rad) -- "
              "SAME situation as the vqa_rad_open/pathvqa_open cells that already use pooled4; not a held-out "
              "cross-dataset transfer. K=8 candidates + judge labels reused from the existing sc8 pipeline "
              "(run_openvqa.py, same as the sibling dumps); only the pooled4-verifier scores are newly computed."),
        transfer_dump=tpath,
    )
    outp = J(f"results/cascade_methods/artifacts/{DS}_bestofN.json")
    os.makedirs(os.path.dirname(outp), exist_ok=True)
    json.dump({"summary": summary, "dump": dump}, open(outp, "w"), indent=1)

    print("\n" + "=" * 84)
    print(f"SLAKE-open best-of-8 verifier dump  (n={len(dump)}, verifier={ADAPTER})")
    print("=" * 84)
    print(f"  verifier best-of-8 SELECTION : {bo8:.4f}")
    print(f"  first-sample (1 draw)        : {sl1:.4f}")
    print(f"  self-consistency modal       : {greedy_modal:.4f}   (dump greedy_ok)")
    print(f"  oracle@8 (ceiling)           : {oracle:.4f}")
    print(f"  --- external references ---")
    print(f"  7B greedy-t0 (current fallback cheap leg) : {greedy_t0}")
    print(f"  32B-no-think (strong leg)                 : {acc32nt}")
    print(f"  d(bo8 - greedy_t0)   = {summary['d_bo8_vs_greedy_t0']}")
    print(f"  d(bo8 - 32B-nt)      = {summary['d_bo8_vs_32b_nothink']}")
    print(f"\nwrote:\n  {tpath}\n  {ckpt}\n  {outp}")
    return summary


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--model_path", default="lingshu-medical-mllm/Lingshu-7B")
    ap.add_argument("--report_only", action="store_true", help="skip GPU scoring; assemble+report from ckpt")
    A = ap.parse_args()
    if A.report_only:
        ckpt = J(f"{CK}/ckpt_{DS}_{TAG}_bestofN_verified.jsonl")
    else:
        ckpt = score_dump(A)
    assemble_and_report(ckpt)
