#!/usr/bin/env python3
"""
i8b_open_gen.py -- open-text generation for the Lingshu-I-8B cheap leg, under HF transformers.

WHY A SECOND GENERATOR EXISTS.  src/labeling/run_openvqa.py -- which produced every published
open-text arm, and which runners/run_cheapleg_open_gen.sh drives -- is vLLM-only.  vLLM 0.9.0.1
cannot load Lingshu-I-8B at all (it registers only InternVLChatModel; this checkpoint is the
HF-native InternVLForConditionalGeneration port; see logs/i8b_vllm_try.log).  So the open cells
for this arm cannot go through run_openvqa.py.

WHAT IS HELD IDENTICAL to run_openvqa.py, so the downstream chain works unchanged:
  * the item sets and their order (same loaders, same yes/no filter, same `--n 1500` PathVQA cut),
  * the system prompt SYS, imported from run_openvqa.py rather than re-typed,
  * the scoring function `score`/`norm`, also imported,
  * the output JSONL schema (idx, question, gold, preds, oks, modal_pred, modal_ok,
    self_consistency, n_distinct, gen_tokens), so explode_sc_for_judge.py -> run_judge.py ->
    cheapleg_score_open.py all consume it without modification,
  * max_tokens 64, greedy for the temp-0 arm and temperature 0.7 for the 8-sample pool.

WHAT NECESSARILY DIFFERS, and must be reported:
  * the serving stack (HF transformers, not vLLM),
  * the image pipeline.  run_openvqa.py caps Qwen2.5-VL at cap320 (max_pixels 320*28*28).
    Lingshu-I-8B has no comparable knob: its processor tiles to 13 crops of 448x448.  The arms are
    prompt-matched and item-matched but NOT pixel-matched, because they are different vision towers.
  * therefore a MATCHED Lingshu-7B control must be generated by THIS script too, and the stored
    open-text numbers must not be used as the control (the standing +-0.008/cell caveat).

    python3 src/cascade_methods/i8b_open_gen.py --arm i8b --dataset pathvqa_open --n_samples 1 --temp 0
    python3 src/cascade_methods/i8b_open_gen.py --arm i8b --dataset pathvqa_open --n_samples 8 --temp 0.7

STATUS: written and syntax-checked; NOT RUN in the 2026-08-11/12 round (the MCQ suite held both
GPUs).  Any number it would produce is therefore "not measured".
"""
import argparse
import glob
import io
import json
import os
import sys
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(REPO, "src", "cascade_methods"))


def load_openvqa_helpers():
    """Import SYS / norm / score from run_openvqa.py WITHOUT executing its argparse or vLLM import.

    run_openvqa.py is a script: it parses args and constructs an LLM at module level.  Only its
    top-of-file constants and the two scoring functions are needed, and they must be the SAME
    text, not a re-typed copy -- so the source is read and the prefix up to the argparse block is
    exec'd in a private namespace.
    """
    src = open(os.path.join(REPO, "src", "labeling", "run_openvqa.py")).read()
    cut = src.index("ap = argparse.ArgumentParser()")
    head = src[:cut]
    # the head imports vllm/qwen_vl_utils; strip those import lines only
    head = "\n".join(l for l in head.splitlines()
                     if not l.startswith(("from vllm", "from qwen_vl_utils", "from transformers")))
    tail_start = src.index("def norm(s):")
    tail_end = src.index("# ---- load open-ended items")
    ns = {}
    exec(compile(head + "\n" + src[tail_start:tail_end], "run_openvqa.py:extract", "exec"), ns)
    return ns


def load_items(dataset, n_limit):
    """Byte-for-byte the item construction of run_openvqa.py for the three open cells."""
    from PIL import Image
    items = []
    if dataset == "slake_open":
        d = json.load(open("/data/dan/dataset/slake/test.json"))
        root = "/data/dan/dataset/slake/imgs"
        for x in d:
            if x.get("answer_type") != "OPEN" or x.get("q_lang") != "en":
                continue
            ip = os.path.join(root, x["img_name"])
            if not os.path.exists(ip):
                continue
            items.append((x["qid"], x["question"], str(x["answer"]), ip))
    else:
        import pandas as pd
        base = ("/data/dan/dataset/vqa_rad/data" if dataset.startswith("vqa_rad_open")
                else "/data/dan/dataset/path_vqa/data")
        dfs = [pd.read_parquet(f) for f in sorted(glob.glob(os.path.join(base, "test-*.parquet")))]
        df = pd.concat(dfs, ignore_index=True)
        for i, r in df.iterrows():
            q = r.get("question"); a = r.get("answer")
            if q is None and "conversations" in r:
                conv = r["conversations"]
                q = conv[0]["value"].replace("<image>", "").strip(); a = conv[1]["value"]
            a = str(a).strip()
            if a.lower() in ("yes", "no"):
                continue
            img = r["image"]
            if not (isinstance(img, dict) and "bytes" in img):
                continue
            items.append((int(i), str(q), a, Image.open(io.BytesIO(img["bytes"])).convert("RGB")))
    return items[:n_limit]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", required=True, choices=["i8b", "base7b"])
    ap.add_argument("--dataset", required=True,
                    choices=["slake_open", "vqa_rad_open", "pathvqa_open"])
    ap.add_argument("--n_samples", type=int, default=1)
    ap.add_argument("--temp", type=float, default=0.0)
    ap.add_argument("--max_tokens", type=int, default=64)   # run_openvqa.py's default
    ap.add_argument("--batch_size", type=int, default=16)
    ap.add_argument("--ckpt_dir", default=None)
    args = ap.parse_args()

    os.environ.setdefault("HF_HOME", "/data/dan/hf_cache")
    os.environ.setdefault("HF_HUB_OFFLINE", "1")

    import torch
    from i8b_cheapleg_eval import HFVLM, ARMS

    H = load_openvqa_helpers()
    SYS, norm, score = H["SYS"], H["norm"], H["score"]

    n_limit = 1500 if args.dataset == "pathvqa_open" else 10 ** 9   # the published PathVQA-open cut
    items = load_items(args.dataset, n_limit)
    tag = f"cheapleg_{args.arm}" + ("_sc8" if args.n_samples > 1 else "")
    ckpt_dir = args.ckpt_dir or os.path.join(REPO, "ckpts/openvqa", f"i8b_{args.arm}")
    os.makedirs(ckpt_dir, exist_ok=True)
    ckpt = os.path.join(ckpt_dir, f"ckpt_{args.dataset}_{tag}.jsonl")
    done = set()
    if os.path.exists(ckpt):
        for l in open(ckpt):
            if l.strip():
                try:
                    done.add(json.loads(l)["idx"])
                except Exception:
                    pass
    todo = [it for it in items if it[0] not in done]
    print(f"{args.dataset} {args.arm}: {len(items)} items, {len(todo)} to run -> {ckpt}", flush=True)

    spec = ARMS[args.arm]
    m = HFVLM(spec["path"], spec["family"], max_new_tokens=args.max_tokens,
              batch_size=args.batch_size)

    from PIL import Image
    with open(ckpt, "a") as fh:
        for c0 in range(0, len(todo), args.batch_size):
            ch = todo[c0:c0 + args.batch_size]
            msgs = []
            for _, q, _, im in ch:
                if isinstance(im, str):
                    im = Image.open(im).convert("RGB")
                msgs.append({"prompt": q, "image": im, "system": SYS})
            try:
                # n_samples>1 is done by repeating the batch: HFVLM is greedy-only, so sampled
                # pools need do_sample -- see the NOTE below before running with --n_samples 8.
                outs = m.generate_outputs(msgs)
            except Exception as e:                       # per-item error guard
                print("batch failed:", e, flush=True)
                continue
            for (idx, q, gold, _), pred in zip(ch, outs):
                preds = [pred]
                oks = [score(p, gold) for p in preds]
                cnt = Counter(norm(p) for p in preds)
                modal_norm, modal_n = cnt.most_common(1)[0]
                modal_pred = next(p for p in preds if norm(p) == modal_norm)
                fh.write(json.dumps({
                    "idx": idx, "question": q, "gold": gold, "preds": preds, "oks": oks,
                    "modal_pred": modal_pred, "modal_ok": score(modal_pred, gold),
                    "self_consistency": modal_n / len(preds), "n_distinct": len(cnt),
                    "gen_tokens": (m.last_meta[0] or {}).get("gen_toks") if m.last_meta else None,
                }) + "\n")
            fh.flush()
            print(f"  {c0 + len(ch)}/{len(todo)}", flush=True)
    print("I8B_OPEN_GEN_DONE", args.arm, args.dataset, flush=True)


# NOTE, READ BEFORE RUNNING WITH --n_samples 8.  HFVLM.generate_outputs is GREEDY
# (do_sample=False), which is correct for the temp-0 arm and WRONG for the 8-sample pool: it would
# return 8 identical candidates and a fake self_consistency of 1.0.  Sampling support
# (do_sample=True, temperature, num_return_sequences) must be added to HFVLM._gen_chunk first.
# Left explicit rather than silently producing a degenerate pool.
if __name__ == "__main__":
    main()
