#!/usr/bin/env python3
"""resolution_open_generate.py -- SWEEP 2: the OPEN-TEXT GENERATOR resolution sweep.

WHAT IS NEW HERE.  results/cascade_methods/artifacts/vram_levers_2026-08-12.json closes the
VERIFIER's resolution arm and leaves this hole open, verbatim, under `not_measured`:

    "open-text GENERATOR accuracy vs resolution": "STILL OPEN. open_half_levers moves the
     VERIFIER's max_pixels only; the 8 candidates it ranks were generated once, at the deployed
     cap320.  What a lower GENERATOR resolution does to the candidate pool (and hence to coverage
     ...) is not measured here -- it would need fresh generation plus a judge pass, in a matched
     serving config."

This script is that fresh generation.  Every arm -- INCLUDING the cap320 control that reproduces
the deployed configuration -- is generated by THIS script in THIS session, so the +-0.008 open-text
reproducibility caveat cannot contaminate a cap-vs-cap delta.  A stored number from an older
serving config is NEVER used as a control.

FIDELITY TO run_openvqa.py.  The system prompt, the item loaders, the answer extractor, the
exact-match scorer, the chat template and the sampling parameters are copied VERBATIM from
src/labeling/run_openvqa.py (which produced the deployed pool).  The only intended differences:
  * max_pixels is a command-line argument instead of a 5-value cap ladder, so the harness
    default (12,845,056) is reachable;
  * SamplingParams carries an explicit seed, so >=3 generation seeds are drawable.
Both differences are asserted in the artifact.  A null test (--temp 0 --n_samples 1 --max_pixels
250880) reproduces the stored deployed greedy dump; its agreement rate is reported, not assumed.

    HF_HOME=/data/dan/hf_cache CUDA_VISIBLE_DEVICES=0 python3 \
      src/cascade_methods/resolution_open_generate.py --dataset slake_open \
      --max_pixels 250880 --n_samples 8 --temp 0.7 --seed 0
"""
import argparse
import glob
import io
import json
import math
import os
import re
import string
import time
from collections import Counter

import numpy as np
from PIL import Image
from qwen_vl_utils import process_vision_info
from transformers import AutoProcessor
from vllm import LLM, SamplingParams

# --- verbatim from src/labeling/run_openvqa.py -----------------------------------------------
SYS = ("You are an expert medical image analyst. Answer the question with a short, specific "
       "phrase. Do not explain.")
MIN_PX = 4 * 28 * 28


def norm(s):
    s = str(s).lower().strip()
    s = re.sub(r"\b(the|a|an|is|are|of|in|on|at|this|image|picture)\b", " ", s)
    s = s.translate(str.maketrans("", "", string.punctuation))
    return re.sub(r"\s+", " ", s).strip()


def score(pred, gold):
    p, g = norm(pred), norm(gold)
    if not p:
        return 0
    if p == g:
        return 1
    if g and (g in p.split() or p in g.split() or g in p or p in g):
        return 1
    return 0
# ----------------------------------------------------------------------------------------------


def load_items(dataset, limit=100000):
    """verbatim item order + filters from run_openvqa.py (test split only)."""
    items = []
    if dataset == "slake_open":
        d = json.load(open("/data/dan/dataset/slake/test.json"))
        root = "/data/dan/dataset/slake/imgs"
        for x in d:
            if x.get("answer_type") != "OPEN" or x.get("q_lang") != "en":
                continue
            ip = os.path.join(root, x["img_name"])
            if not os.path.exists(ip):
                continue
            items.append((x["qid"], x["question"], str(x["answer"]), ip))
    else:
        import pandas as pd
        base = ("/data/dan/dataset/vqa_rad/data" if dataset.startswith("vqa_rad_open")
                else "/data/dan/dataset/path_vqa/data")
        df = pd.concat([pd.read_parquet(f) for f in sorted(glob.glob(os.path.join(base, "test-*.parquet")))],
                       ignore_index=True)
        for i, r in df.iterrows():
            q = r.get("question")
            a = r.get("answer")
            if q is None and "conversations" in r:
                conv = r["conversations"]
                q = conv[0]["value"].replace("<image>", "").strip()
                a = conv[1]["value"]
            a = str(a).strip()
            if a.lower() in ("yes", "no"):
                continue
            img = r["image"]
            if isinstance(img, dict) and "bytes" in img:
                pil = Image.open(io.BytesIO(img["bytes"])).convert("RGB")
            else:
                continue
            items.append((int(i), str(q), a, pil))
    return items[:limit]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model_path", default="lingshu-medical-mllm/Lingshu-7B")
    ap.add_argument("--datasets", nargs="+", default=["slake_open", "vqa_rad_open", "pathvqa_open"])
    ap.add_argument("--max_pixels", type=int, required=True)
    ap.add_argument("--cap_name", required=True)
    ap.add_argument("--n_samples", type=int, default=8)
    ap.add_argument("--temp", type=float, default=0.7)
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2],
                    help="per-request SamplingParams seeds; one arm per seed, one model load for all")
    ap.add_argument("--greedy", action="store_true",
                    help="also run a temperature-0, n=1 greedy arm at this cap")
    ap.add_argument("--n", type=int, default=100000)
    ap.add_argument("--ckpt_dir", default="ckpts/openvqa/resolution_sweep")
    ap.add_argument("--tp", type=int, default=1)
    ap.add_argument("--gpu_mem", type=float, default=0.85)
    ap.add_argument("--max_model_len", type=int, default=4096)
    ap.add_argument("--max_tokens", type=int, default=64)
    A = ap.parse_args()
    os.makedirs(A.ckpt_dir, exist_ok=True)
    NLIM = {"pathvqa_open": 1500}          # run_openvqa_pathvqa.sh used --n 1500

    proc = AutoProcessor.from_pretrained(A.model_path, trust_remote_code=True)
    llm = LLM(model=A.model_path, tensor_parallel_size=A.tp, dtype="bfloat16",
              gpu_memory_utilization=A.gpu_mem, max_model_len=A.max_model_len,
              limit_mm_per_prompt={"image": 4}, trust_remote_code=True, seed=0)

    # GREEDY FIRST: the T=0 arm is 8x cheaper per item and answers the "does resolution move the
    # model's single decode" question on its own, so it is generated before the sampled arms. On a
    # contended card a truncated cap then still has its greedy row.
    arms = []
    if A.greedy:
        arms.append((0, 0.0, 1, f"{A.cap_name}_t0"))
    arms += [(s, A.temp, A.n_samples, f"{A.cap_name}_s{s}") for s in A.seeds]
    cache = {}
    for seed, temp, nsamp, tagbase in arms:
      sp = SamplingParams(temperature=temp, max_tokens=A.max_tokens, n=nsamp,
                          logprobs=5, seed=seed)
      for ds in A.datasets:
        if ds not in cache:
            cache[ds] = load_items(ds, min(A.n, NLIM.get(ds, 100000)))
        items = cache[ds]
        tag = tagbase
        ckpt = os.path.join(A.ckpt_dir, f"ckpt_{ds}_{tag}.jsonl")
        done = set()
        if os.path.exists(ckpt):
            for l in open(ckpt):
                if l.strip():
                    try:
                        done.add(json.loads(l)["idx"])
                    except Exception:
                        pass
        todo = [it for it in items if it[0] not in done]
        print(f"{ds} {tag}: {len(items)} items, {len(todo)} to run -> {ckpt}", flush=True)
        t0 = time.time()
        CH = 64
        with open(ckpt, "a") as fh:
            for c0 in range(0, len(todo), CH):
                ch = todo[c0:c0 + CH]
                reqs = []
                ntok = []
                for (_, q, _, im) in ch:
                    msgs = [{"role": "system", "content": SYS},
                            {"role": "user", "content": [
                                {"type": "image", "image": im, "max_pixels": A.max_pixels,
                                 "min_pixels": MIN_PX}, {"type": "text", "text": q}]}]
                    text = proc.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
                    imgs, _ = process_vision_info(msgs)
                    req = {"prompt": text}
                    if imgs:
                        req["multi_modal_data"] = {"image": imgs}
                        ntok.append(int(imgs[0].size[0] * imgs[0].size[1] / (28 * 28))
                                    if hasattr(imgs[0], "size") else -1)
                    else:
                        ntok.append(-1)
                    reqs.append(req)
                try:
                    outs = llm.generate(reqs, sp)
                except Exception as e:      # per-chunk error guard
                    print(f"   CHUNK FAIL {c0}: {type(e).__name__} {e}", flush=True)
                    continue
                for (idx, q, gold, _), o, vt in zip(ch, outs, ntok):
                    try:
                        preds = [c.text.strip() for c in o.outputs]
                        oks = [score(p, gold) for p in preds]
                        cnt = Counter(norm(p) for p in preds)
                        modal_norm, modal_n = cnt.most_common(1)[0]
                        modal_pred = next(p for p in preds if norm(p) == modal_norm)
                        margin = conf = None
                        try:
                            _ps = sorted([math.exp(v.logprob)
                                          for v in o.outputs[0].logprobs[0].values()], reverse=True)
                            conf = round(_ps[0], 4)
                            margin = round(_ps[0] - (_ps[1] if len(_ps) > 1 else 0.0), 4)
                        except Exception:
                            pass
                        fh.write(json.dumps({
                            "idx": idx, "question": q, "gold": gold, "preds": preds, "oks": oks,
                            "modal_pred": modal_pred, "modal_ok": int(score(modal_pred, gold)),
                            "self_consistency": round(modal_n / len(preds), 4),
                            "n_distinct": len(cnt), "margin": margin, "conf": conf,
                            "prompt_tokens": len(o.prompt_token_ids),
                            "vision_px_tokens": vt,
                            "gen_tokens_all": [len(c.token_ids) for c in o.outputs]}) + "\n")
                    except Exception as e:  # per-item error guard
                        print(f"   ITEM FAIL {idx}: {type(e).__name__} {e}", flush=True)
                fh.flush()
                print(f"   [{min(c0 + CH, len(todo))}/{len(todo)}] "
                      f"{(min(c0 + CH, len(todo))) / max(1e-9, time.time() - t0):.1f}/s", flush=True)
        print(f"DONE {ds} {tag} in {(time.time() - t0) / 60:.1f} min", flush=True)


if __name__ == "__main__":
    main()
