#!/usr/bin/env python3
"""selfcons_slots.py -- IS AN n=8 vLLM POOL SLOT-EXCHANGEABLE?

Found while running ATTACK 2: on PMC_VQA the per-SLOT accuracy of the T=0.4 n=8 pool ranges
0.4453 (slot 4) to 0.5813 (slot 7).  If that is real, then

  * "N=2" implemented as a subset of an 8-pool is not the same experiment as "draw 2 samples", and
  * any vote rule that breaks ties by slot INDEX inherits a position bias,

both of which would contaminate the N-curve that is this round's deliverable.  So it is tested
before any curve is reported, not after.

TEST (per cell, per pool): the statistic is the max-minus-min of the eight per-slot accuracies.
The null shuffles the slot ORDER INDEPENDENTLY WITHIN EACH ITEM, which preserves every item's pool
composition and every within-item correlation and destroys only the position information.  2000
permutations, seed 20260817.

  python3 src/cascade_methods/selfcons_slots.py
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, ROOT)

import selfcons_lib as S                                                  # noqa: E402
import closed_as_open_lib as L                                            # noqa: E402
from selfcons_suite import mcq_load, letter_of, MCQ_CELLS, OPEN_DS, OPEN_CELL   # noqa: E402

NPERM, SEED = 2000, 20260817


def perm_test(Y):
    """Y: (n_items, 8) 0/1 labels in generation slot order."""
    n, M = Y.shape
    obs_slot = Y.mean(0)
    obs = float(obs_slot.max() - obs_slot.min())
    rng = np.random.default_rng(SEED)
    null = np.empty(NPERM)
    for b in range(NPERM):
        idx = np.argsort(rng.random((n, M)), axis=1)
        Z = np.take_along_axis(Y, idx, axis=1)
        m = Z.mean(0)
        null[b] = m.max() - m.min()
    p = float((null >= obs).mean())
    return {"n_items": int(n), "per_slot_accuracy": [round(float(x), 6) for x in obs_slot],
            "observed_max_minus_min": round(obs, 6),
            "null_mean": round(float(null.mean()), 6),
            "null_p95": round(float(np.percentile(null, 95)), 6),
            "p_value": round(p, 6),
            "slot_order_matters": bool(p < 0.05),
            "nperm": NPERM, "seed": SEED}


def main():
    out = {"title": "IS AN n=8 vLLM POOL SLOT-EXCHANGEABLE? -- permutation test on per-slot accuracy",
           "date": S.DATE,
           "why": "found while running ATTACK 2; a non-exchangeable pool would make an N-subset curve "
                  "a different experiment from an N-sample run, and would give any index tie-break a "
                  "position bias.",
           "null": "slot order shuffled INDEPENDENTLY WITHIN EACH ITEM (preserves pool composition "
                   "and within-item correlation, destroys only position)",
           "cells": {}}

    # --- MCQ pools (ckpts/closed_as_open_mcq, generated by closed_as_open_mcq_sc.py) -------------
    for cell in MCQ_CELLS:
        s = mcq_load(cell, "mcq_s8")
        Y, T = [], []
        for i in sorted(s):
            r = s[i]
            gold = str(r["gold"]).strip().lower()
            k = int(r["k"])
            Y.append([int(letter_of(p, k) == gold) for p in r["preds"]])
            T.append(list(r.get("gen_tokens", [0] * 8)))
        out["cells"][cell] = perm_test(np.asarray(Y, float))
        out["cells"][cell]["currency"] = "letter_em"
        out["cells"][cell]["per_slot_mean_gen_tokens"] = [round(float(x), 3)
                                                          for x in np.asarray(T, float).mean(0)]
        out["cells"][cell]["generator"] = "src/cascade_methods/closed_as_open_mcq_sc.py, vLLM " \
                                          "SamplingParams(n=8, seed=20260813, T=0.4)"
        print(cell, json.dumps({k: v for k, v in out["cells"][cell].items()
                                if k in ("observed_max_minus_min", "null_p95", "p_value",
                                         "slot_order_matters")}), flush=True)

    # --- closed pools (ckpts/closed_as_open, generated by closed_as_open_gen.py) ------------------
    for cell in L.CELLS:
        g = L.load_gen(cell, "closedD_s8")
        Y, T = [], []
        for i in sorted(g):
            r = g[i]
            Y.append([L.em_harness(cell, r["gold"], p) for p in r["preds"]])
            T.append(list(r.get("gen_tokens", [0] * 8)))
        out["cells"][cell] = perm_test(np.asarray(Y, float))
        out["cells"][cell]["currency"] = "MedEvalKit deployed closed grader"
        out["cells"][cell]["per_slot_mean_gen_tokens"] = [round(float(x), 3)
                                                          for x in np.asarray(T, float).mean(0)]
        out["cells"][cell]["generator"] = "src/cascade_methods/closed_as_open_gen.py, vLLM " \
                                          "SamplingParams(n=8, seed=20260813, T=0.4)"
        print(cell, json.dumps({k: v for k, v in out["cells"][cell].items()
                                if k in ("observed_max_minus_min", "null_p95", "p_value",
                                         "slot_order_matters")}), flush=True)

    # --- open pools (ckpts/openvqa/decoding_sweep, generated by decoding_sweep_gen.py) ------------
    from src.cascade_methods.decoding_sweep_analyse import load_pool
    for sd in ["s0", "s1", "s2"]:
        p = load_pool(f"T04_{sd}", strict=False)
        for ds in OPEN_DS:
            cell = OPEN_CELL[ds]
            Y, T = [], []
            for (d, idx), r in sorted(p.items(), key=lambda kv: (str(kv[0][0]), str(kv[0][1]))):
                if d != ds:
                    continue
                Y.append([int(x) for x in r["oks_em"]])
                T.append(list(r.get("gen_tokens_all", [0] * 8)))
            key = f"{cell}__T04_{sd}"
            out["cells"][key] = perm_test(np.asarray(Y, float))
            out["cells"][key]["currency"] = "normalised exact match (oks_em)"
            out["cells"][key]["per_slot_mean_gen_tokens"] = [round(float(x), 3)
                                                             for x in np.asarray(T, float).mean(0)]
            out["cells"][key]["generator"] = "src/cascade_methods/decoding_sweep_gen.py, vLLM " \
                                             "SamplingParams(n=8, T=0.4)"
            print(key, json.dumps({k: v for k, v in out["cells"][key].items()
                                   if k in ("observed_max_minus_min", "null_p95", "p_value",
                                            "slot_order_matters")}), flush=True)

    # --- the FROZEN deployed T=0.7 pool, the one every published best-of-8 number rests on ---------
    from src.training_methods import genframe_data as G
    fro = G.load_items()
    for ds in OPEN_DS:
        Y = np.asarray([[int(x) for x in it["sl"]] for it in fro if it["ds"] == ds], float)
        key = f"{OPEN_CELL[ds]}__FROZEN_deployed_T07"
        out["cells"][key] = perm_test(Y)
        out["cells"][key]["currency"] = "32B LLM judge (the frozen endpoint's own slot labels)"
        out["cells"][key]["generator"] = "runners/run_openvqa_lingshu7b.sh / run_openvqa_pathvqa.sh, " \
                                         "June 2026, vLLM n=8 at T=0.7 -- the pool EVERY published " \
                                         "best-of-8 / oracle@8 / coverage number in this project " \
                                         "rests on"
        print(key, json.dumps({k: v for k, v in out["cells"][key].items()
                               if k in ("observed_max_minus_min", "null_p95", "p_value",
                                        "slot_order_matters")}), flush=True)

    # --- WHAT DRIVES IT: per-slot ANSWER-SPACE marginal, length, and agreement with greedy --------
    mech = {"question": "if the slots are not exchangeable, WHAT differs between them -- reasoning "
                        "quality, answer length, or the answer-space marginal (this round's theme)?",
            "cells": {}}
    from selfcons_suite import mcq_load as _ml
    for cell in MCQ_CELLS:
        g, s = _ml(cell, "mcq_g"), _ml(cell, "mcq_s8")
        idx = sorted(set(g) & set(s))
        K = max(int(g[i]["k"]) for i in idx)
        Mmarg = np.zeros((8, K))
        acc = np.zeros(8)
        agree = np.zeros(8)
        gold_marg = np.zeros(K)
        for i in idx:
            k = int(g[i]["k"])
            gold = str(g[i]["gold"]).strip().lower()
            gl = letter_of(g[i]["preds"][0], k)
            if gold and ord(gold[0]) - 97 < K:
                gold_marg[ord(gold[0]) - 97] += 1
            for j, p in enumerate(s[i]["preds"]):
                x = letter_of(p, k)
                if x:
                    Mmarg[j][ord(x) - 97] += 1
                acc[j] += int(x == gold)
                agree[j] += int(x == gl)
        n = len(idx)
        Mmarg /= n
        acc /= n
        agree /= n
        gold_marg /= n
        # "on-marginal mass" = how much of a slot's letter output lands on the letters gold favours
        onmass = Mmarg @ gold_marg
        T = np.asarray([s[i].get("gen_tokens", [0] * 8) for i in idx], float).mean(0)
        mech["cells"][cell] = {
            "gold_letter_marginal": [round(float(x), 4) for x in gold_marg],
            "per_slot_letter_marginal": [[round(float(y), 4) for y in r] for r in Mmarg],
            "per_slot_accuracy": [round(float(x), 4) for x in acc],
            "per_slot_agreement_with_greedy": [round(float(x), 4) for x in agree],
            "per_slot_mean_gen_tokens": [round(float(x), 3) for x in T],
            "corr_onmarginal_mass_vs_accuracy": round(float(np.corrcoef(onmass, acc)[0, 1]), 4),
            "corr_gen_tokens_vs_accuracy": round(float(np.corrcoef(T, acc)[0, 1]), 4),
            "agreement_spread": round(float(agree.max() - agree.min()), 4),
        }
    for cell in L.CELLS:
        g, s = L.load_gen(cell, "closedD_g"), L.load_gen(cell, "closedD_s8")
        idx = sorted(set(g) & set(s))
        acc = np.zeros(8)
        yes = np.zeros(8)
        agree = np.zeros(8)
        goldyes = 0.0
        npar = np.zeros(8)
        for i in idx:
            gold = str(g[i]["gold"]).strip().lower()
            goldyes += int(gold == "yes")
            gp = L.norm_text(g[i]["preds"][0])
            for j, p in enumerate(s[i]["preds"]):
                acc[j] += L.em_harness(cell, g[i]["gold"], p)
                pol = L.polarity(p)
                if pol is not None:
                    npar[j] += 1
                    yes[j] += int(pol == "yes")
                agree[j] += int(L.norm_text(p) == gp)
        n = len(idx)
        mech["cells"][cell] = {
            "gold_P_yes": round(goldyes / n, 4),
            "per_slot_accuracy": [round(float(x), 4) for x in acc / n],
            "per_slot_P_says_yes": [round(float(y / m), 4) if m else None
                                    for y, m in zip(yes, npar)],
            "per_slot_agreement_with_greedy": [round(float(x), 4) for x in agree / n],
            "agreement_spread": round(float((agree / n).max() - (agree / n).min()), 4),
            "note": "gold_P_yes is meaningful only where the cell is a yes/no judgement cell; "
                    "SLAKE_closed is a short-phrase cell and its P_yes is over the subset of "
                    "responses that parse as a polarity at all",
        }
    out["MECHANISM_what_differs_between_slots"] = mech

    sig = [k for k, v in out["cells"].items() if v.get("slot_order_matters")]
    out["VERDICT"] = {
        "pools_where_slot_order_matters_at_p<0.05": sig,
        "n_pools_tested": len(out["cells"]) - 0,
        "consequence": "for any pool listed above, an index tie-break carries a position bias and the "
                       "N-curve must also be reported with an ORDER-FREE tie-break (random among the "
                       "tied classes). selfcons_suite.py reports index, order-free and first-N-prefix.",
        "MEASURED_not_inferred": "the permutation test, the per-slot marginals, the per-slot token "
                                 "counts and the per-slot greedy agreement are all measurements in "
                                 "this file.",
        "HYPOTHESIS_not_measured": "the pattern is CONSISTENT WITH a fixed per-request seed making "
                                   "the n sequences a fixed QUANTILE FAN rather than n i.i.d. draws: "
                                   "the per-slot agreement with greedy is a stable per-slot constant, "
                                   "the deviation is in the ANSWER-SPACE MARGINAL and not in length, "
                                   "and the effect is large where the answer is essentially one token "
                                   "drawn from a small biased space (PMC letters, PATH_VQA yes/no) and "
                                   "washes out on multi-token open text. THIS MECHANISM IS NOT PROVEN "
                                   "HERE. Proving it needs an A/B of one fixed seed versus per-request "
                                   "seeds, which is a GPU job and was not run.",
    }
    p = S.dump_part("slot_exchangeability.json", out)
    print("wrote", p)
    print("VERDICT:", json.dumps(out["VERDICT"]))


if __name__ == "__main__":
    main()
