#!/usr/bin/env python3
"""verifier_hparams_score.py -- KNOB 3: sweep the VERIFIER's OWN scoring resolution.

WHAT MOVES AND WHAT DOES NOT
----------------------------
The GENERATOR is FROZEN.  Every arm scores the SAME deployed candidate pool -- the stored
transfer dumps in ckpts/train/lora_verifier_disjoint (2345 items x 8 slots, generated by
run_openvqa.py at cap320 = 250,880 px), with the SAME judge labels `sl`.  Nothing is
regenerated, so the project's +-0.008 open-text regeneration caveat does not apply to any
delta in this round.  The ONLY variable is the verifier's `max_pixels`.

This is the mirror image of resolution_sweep_2026-08-13, which moved the generator and held
the verifier at 1,003,520.  Together the two rounds cover the deployed pipeline's resolution
inconsistency: generator 250,880 vs verifier 1,003,520 (4.0x).

THE CONFOUND, STATED UP FRONT
-----------------------------
ckpts/train/lora_verifier_disjoint/train_config.json records max_pixels 1,003,520.  Scoring at
any other resolution is a TRAIN/INFERENCE MISMATCH as well as a resolution change.  The design
cannot fully separate them with one adapter; what it CAN do is report the deployed rung as the
zero-mismatch point and let the shape of the curve either side of it speak.  A monotone curve
through 1,003,520 is a resolution effect; a peak AT 1,003,520 is consistent with mismatch cost.

DETERMINISM / CACHING
---------------------
With the verifier fixed at one resolution, P(yes) is a pure function of
(image, question, RAW answer string), so the unit of work is the DISTINCT triple
(ds, idx, raw answer): 8,965 of them over the 18,760 slots.  Scores are keyed by that triple.

NUMERICS PINNED (all recorded in the output header):
  TF32 OFF (matmul + cudnn), bf16, flash_attention_2, batch 1 (the deployed batch),
  min_pixels 3,136 held fixed, HF transformers -- NEVER vLLM (vLLM 0.9.0.1 drops all 192
  visual.* LoRA modules: 0.775204 HF vs 0.702997 vLLM).

NULL TEST (--null_test N): re-score N stored (item, candidate) pairs at the DEPLOYED 1,003,520
and print the max abs deviation from the score in the transfer dump.  This is the same-code-path
reproduction check and it must be run before any arm is trusted.

  HF_HOME=/data/dan/hf_cache CUDA_VISIBLE_DEVICES=0 python3 \
      src/cascade_methods/verifier_hparams_score.py --null_test 200
  HF_HOME=/data/dan/hf_cache CUDA_VISIBLE_DEVICES=0 python3 \
      src/cascade_methods/verifier_hparams_score.py --max_pixels 250880
"""
import argparse
import glob
import io
import json
import math
import os
import time

import numpy as np
import torch
from PIL import Image
from peft import PeftModel
from qwen_vl_utils import process_vision_info
from transformers import AutoModelForImageTextToText, AutoProcessor

ROOT = os.path.expanduser("~/medvlthinker-imgdiff-compute")
DUMPS = os.path.join(ROOT, "ckpts/train/lora_verifier_disjoint")
OUTDIR = os.path.join(ROOT, "ckpts/openvqa/verifier_hparams")
DS = ["slake_open", "vqa_rad_open", "pathvqa_open"]
DUMPNAME = {"slake_open": "slake", "vqa_rad_open": "vqa_rad", "pathvqa_open": "pathvqa"}

# verbatim from src/training_methods/verifier_transfer_eval.py (the script that produced the
# deployed transfer dumps).  MINPX is held fixed in every arm; only MAXPX moves.
DEPLOYED_MAXPX, MINPX = 1280 * 28 * 28, 4 * 28 * 28   # 1,003,520 / 3,136
SYS = ("You are a careful medical exam grader. Given a question and a proposed answer, decide "
       "whether the proposed answer is correct. Respond with only 'Yes' or 'No'.")


def imgs_for(ds):
    """verbatim from verifier_transfer_eval.imgs_for -- same images, same order, same filters."""
    m = {}
    if ds == "slake_open":
        for x in json.load(open("/data/dan/dataset/slake/test.json")):
            if x.get("answer_type") == "OPEN" and x.get("q_lang") == "en":
                ip = os.path.join("/data/dan/dataset/slake/imgs", x["img_name"])
                if os.path.exists(ip):
                    m[x["qid"]] = (x["question"], ip)
    else:
        import pandas as pd
        base = ("/data/dan/dataset/vqa_rad/data" if ds == "vqa_rad_open"
                else "/data/dan/dataset/path_vqa/data")
        df = pd.concat([pd.read_parquet(f) for f in
                        sorted(glob.glob(os.path.join(base, "test-*.parquet")))], ignore_index=True)
        for i, r in df.iterrows():
            q = r.get("question")
            a = r.get("answer")
            if q is None and "conversations" in r:
                conv = r["conversations"]
                q = conv[0]["value"].replace("<image>", "").strip()
                a = conv[1]["value"]
            if str(a).strip().lower() in ("yes", "no"):
                continue
            img = r["image"]
            if isinstance(img, dict) and "bytes" in img:
                m[int(i)] = (str(q), Image.open(io.BytesIO(img["bytes"])).convert("RGB"))
    return m


def load_dump_items():
    """The 2345 items in the canonical order genframe_data.DUMP_ORDER."""
    items = []
    for nm in ["slake", "vqa_rad", "pathvqa"]:
        items.extend(json.load(open(os.path.join(DUMPS, f"transfer_dump_{nm}_open_lingshu7b.json"))))
    return items


def distinct_triples():
    """[(ds, idx, raw answer)] -- the unit of work.  Grouped by item so consecutive forwards
    share one image (fewer decodes, and the vision geometry is recorded once per item)."""
    seen, out = set(), []
    for it in load_dump_items():
        for a in it["preds"]:
            k = (it["ds"], it["idx"], a)
            if k not in seen:
                seen.add(k)
                out.append(k)
    return out


def stored_scores():
    """{(ds, idx, raw answer) -> the score in the deployed transfer dump}."""
    c = {}
    for it in load_dump_items():
        for a, s in zip(it["preds"], it["scores"]):
            c[(it["ds"], it["idx"], a)] = float(s)
    return c


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model_path", default="lingshu-medical-mllm/Lingshu-7B")
    ap.add_argument("--adapter", default="ckpts/train/lora_verifier_disjoint")
    ap.add_argument("--max_pixels", type=int, default=DEPLOYED_MAXPX)
    ap.add_argument("--tag", default=None, help="output tag; defaults to px<max_pixels>")
    ap.add_argument("--null_test", type=int, default=0)
    ap.add_argument("--limit", type=int, default=0, help="probe only: score this many triples")
    ap.add_argument("--flush_every", type=int, default=200)
    A = ap.parse_args()

    # ---- pinned numerics -------------------------------------------------------------
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False
    torch.set_num_threads(int(os.environ.get("OMP_NUM_THREADS", "8")))

    os.makedirs(OUTDIR, exist_ok=True)
    tag = A.tag or f"px{A.max_pixels}"
    ckpt = os.path.join(OUTDIR, f"scores_{tag}.jsonl")

    trip = distinct_triples()
    if A.limit:
        rng = np.random.default_rng(0)
        trip = [trip[i] for i in sorted(rng.choice(len(trip), size=min(A.limit, len(trip)),
                                                   replace=False))]
    done = set()
    if os.path.exists(ckpt):
        for l in open(ckpt):
            if l.strip():
                try:
                    r = json.loads(l)
                    done.add((r["ds"], r["idx"], r["ans"]))
                except Exception:
                    pass
    todo = [t for t in trip if t not in done]
    print(f"[{tag}] max_pixels={A.max_pixels}  triples={len(trip)}  already done={len(done)}  "
          f"to score={len(todo)}", flush=True)
    if not todo and not A.null_test:
        return

    proc = AutoProcessor.from_pretrained(A.model_path)
    YES = proc.tokenizer.encode("Yes", add_special_tokens=False)[0]
    NO = proc.tokenizer.encode("No", add_special_tokens=False)[0]
    model = AutoModelForImageTextToText.from_pretrained(
        A.model_path, torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2").to("cuda")
    if A.adapter.lower() == "none":
        # THE MISMATCH CONTROL: the BASE model as a zero-shot verifier.  It was never trained at
        # 1,003,520 (or at anything), so its resolution curve on this identical task/prompt/pool
        # is a PURE resolution effect with no train/inference mismatch anywhere on the ladder.
        print("  BASE MODEL, NO ADAPTER -- the zero-shot mismatch control", flush=True)
    else:
        model = PeftModel.from_pretrained(model, os.path.join(ROOT, A.adapter))
        nvis = sum(1 for n, _ in model.named_parameters() if "lora" in n and "visual." in n)
        print(f"  LoRA tensors on visual.*: {nvis}  (must be 192; 0 means vLLM-style drop)",
              flush=True)
    model.eval()

    IMG = {}

    def _msgs(ds, idx, ans, maxpx):
        if ds not in IMG:
            IMG[ds] = imgs_for(ds)
        q, img = IMG[ds][idx]
        return [{"role": "system", "content": SYS},
                {"role": "user", "content": [
                    {"type": "image", "image": img, "max_pixels": maxpx, "min_pixels": MINPX},
                    {"type": "text", "text": f"Question: {q}\nProposed answer: {ans}\n"
                                             f"Is the proposed answer correct? Answer Yes or No."}]}]

    def pyes(ds, idx, ans, maxpx):
        """Returns (p_yes, n_input_tokens, n_premerge_patches, wall_s).  batch 1 = deployed."""
        msgs = _msgs(ds, idx, ans, maxpx)
        text = proc.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        igs, vids = process_vision_info(msgs)
        enc = proc(text=[text], images=igs, videos=vids, return_tensors="pt",
                   padding=True).to("cuda")
        torch.cuda.synchronize()
        t0 = time.time()
        with torch.no_grad():
            lg = model(**enc).logits[0, -1]
            py = math.exp(lg[YES].item())
            pn = math.exp(lg[NO].item())
        torch.cuda.synchronize()
        w = time.time() - t0
        ntok = int(enc["input_ids"].shape[1])
        # pixel_values rows are PRE-MERGE patches (2x2 spatial merge -> vision tokens = rows/4)
        npatch = int(enc["pixel_values"].shape[0]) if "pixel_values" in enc else 0
        p = py / (py + pn) if (py + pn) > 0 else 0.5
        return p, ntok, npatch, w

    # ---- null test: reproduce the deployed scores at the deployed resolution ----------
    if A.null_test:
        st = stored_scores()
        keys = sorted(st, key=lambda k: (k[0], str(k[1]), k[2]))
        rng = np.random.default_rng(0)
        pick = [keys[i] for i in rng.choice(len(keys), size=min(A.null_test, len(keys)),
                                            replace=False)]
        got = [pyes(ds, idx, a, DEPLOYED_MAXPX)[0] for ds, idx, a in pick]
        dev = np.array([abs(g - st[k]) for g, k in zip(got, pick)])
        rep = {"n": len(dev), "max_abs_dev": float(dev.max()), "mean_abs_dev": float(dev.mean()),
               "n_above_1e_3": int((dev > 1e-3).sum()), "n_above_1e_2": int((dev > 1e-2).sum()),
               "_what": "batch-1 re-score at the DEPLOYED max_pixels 1,003,520 vs the score stored "
                        "in ckpts/train/lora_verifier_disjoint/transfer_dump_*.json. Same prompt, "
                        "same processor path, same adapter."}
        print(f"NULL TEST n={len(dev)} max_abs_dev={dev.max():.6e} mean={dev.mean():.6e} "
              f"n>1e-3={int((dev > 1e-3).sum())}", flush=True)
        json.dump(rep, open(os.path.join(OUTDIR, "null_test_rescore.json"), "w"), indent=1)
        return

    t0 = time.time()
    nfail = 0
    with open(ckpt, "a") as fh:
        for i, (ds, idx, a) in enumerate(todo):
            try:                                   # per-item error guard
                p, ntok, npatch, w = pyes(ds, idx, a, A.max_pixels)
                fh.write(json.dumps({"ds": ds, "idx": idx, "ans": a, "p": p,
                                     "in_tok": ntok, "patch": npatch, "wall_s": round(w, 5)}) + "\n")
            except Exception as e:
                nfail += 1
                print(f"  ITEM FAIL {ds} {idx}: {type(e).__name__} {e}", flush=True)
                fh.write(json.dumps({"ds": ds, "idx": idx, "ans": a, "p": None,
                                     "err": f"{type(e).__name__}: {e}"}) + "\n")
            if (i + 1) % A.flush_every == 0:
                fh.flush()
                el = time.time() - t0
                print(f"  [{i+1}/{len(todo)}] {(i+1)/el:.2f}/s  eta "
                      f"{(len(todo)-i-1)/max((i+1)/el, 1e-9)/60:.1f} min", flush=True)
    print(f"DONE {tag}: {len(todo)} in {(time.time()-t0)/60:.1f} min, {nfail} failures", flush=True)


if __name__ == "__main__":
    main()
