#!/usr/bin/env python3
"""
vram_levers_accuracy.py -- ATTACK 4 part 1b: the ACCURACY half of the resolution-cap frontier.

WHY THIS FILE EXISTS.  Attack 4 asks for an accuracy-vs-VRAM frontier over the image-resolution
lever.  The VRAM half must be measured fresh (src/cascade/measure_vram_levers.py).  The ACCURACY
half does NOT need a fresh run: `runners/run_lingshu_acc.sh` already swept Lingshu-7B over
cap80/cap160/cap320/cap640/fullres on the INTERNAL (MedVLThinker-Eval / NGC) harness, and the five
dumps are on disk under ckpts/acc_gen/lingshu7b/<cap>/.  They are perfectly paired: every one of the
7 cells has an identical idx set in all 5 caps (2000/416/272/3362/1446/554/170).  This script reads
them and computes the paired deltas with CIs.  Re-running that sweep would burn GPU for a number
already measured, and would violate the matched-serving-config rule less safely than reusing arms
generated BY ONE SCRIPT IN ONE CONFIG.

*** TRACK DISCIPLINE -- READ CLAUDE.md SECTION 0's TWO-SPLIT LANDMINE. ***
These dumps are the INTERNAL harness (evaluation context B), NOT MedEvalKit (context A).  Their
PMC-VQA is test_clean.csv (v1, n=2,000, human-verified); the paper's macro cells use test_2.csv
(v2, n=33,430) and the two splits share 6 items.  So:
  * the per-cap DELTAS here are valid -- every cap is the same items, same script, same serving
    config, differing only in max_pixels;
  * the per-cap LEVELS must never be compared against a macro cell level, and the macro-7 computed
    here is labelled `internal_track_macro7` and is NOT the paper's macro-8.

WHAT max_pixels ACTUALLY MEANS HERE.  src/labeling/run_vlm_eval.py:26 sets HIGH_PX = 1280*28*28 and
line 55 divides by CAP_DIV = {fullres:1, cap640:2, cap320:4, cap160:8, cap80:16}.  Qwen2.5-VL
tokenises in 14x14 patches and 2x2-merges, so max_pixels/(28*28) is exactly the MERGED VISION TOKEN
BUDGET: fullres=1280, cap640=640, cap320=320, cap160=160, cap80=80 tokens.  The cap names ARE the
token budgets.  MedEvalKit (harness A) leaves max_pixels at the qwen_vl_utils default 12,845,056 =
a 16,384-token budget, i.e. 12.8x the internal harness's own "fullres" and 51.2x cap320.

    python3 src/cascade_methods/vram_levers_accuracy.py
"""
import json
import os

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "results/cascade_methods/artifacts/_vram_levers_parts")
os.makedirs(OUT, exist_ok=True)

CAPS = ["fullres", "cap640", "cap320", "cap160", "cap80"]
CAP_MAXPX = {"fullres": 1280 * 28 * 28, "cap640": (1280 * 28 * 28) // 2,
             "cap320": (1280 * 28 * 28) // 4, "cap160": (1280 * 28 * 28) // 8,
             "cap80": (1280 * 28 * 28) // 16}
CAP_TOKENS = {c: CAP_MAXPX[c] // (28 * 28) for c in CAPS}
CELLS = ["PMC-VQA", "SLAKE", "VQA-RAD", "PathVQA",
         "MedXpert-Reasoning", "MedXpert-Understanding", "MMMU"]
NBOOT = 10000
SEED = 20260812


def load(cap, cell):
    f = os.path.join(REPO, f"ckpts/acc_gen/lingshu7b/{cap}/ckpt_{cell}_lingshu7b.jsonl")
    d = {}
    for line in open(f):
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except Exception:
            continue
        d[r["idx"]] = r
    return d


def main():
    raw = {cap: {cell: load(cap, cell) for cell in CELLS} for cap in CAPS}

    # ---- pair on idx, per cell, across ALL five caps simultaneously (one shared index order)
    ok = {}          # ok[cell][cap] -> np.array of 0/1, aligned
    meta = {}
    for cell in CELLS:
        ids = sorted(set.intersection(*[set(raw[c][cell]) for c in CAPS]), key=str)
        ok[cell] = {c: np.array([1.0 if raw[c][cell][i].get("ok") else 0.0 for i in ids])
                    for c in CAPS}
        meta[cell] = dict(
            n=len(ids),
            parse_ok={c: round(float(np.mean([1.0 if raw[c][cell][i].get("parse_ok") else 0.0
                                              for i in ids])), 4) for c in CAPS},
            gen_tokens_mean={c: round(float(np.mean([raw[c][cell][i].get("gen_tokens") or 0
                                                     for i in ids])), 2) for c in CAPS})

    # ---- ONE shared bootstrap stream per cell, so every cap's delta is on the same resamples
    rng = np.random.default_rng(SEED)
    boot_idx = {cell: rng.integers(0, meta[cell]["n"], size=(NBOOT, meta[cell]["n"]))
                for cell in CELLS}

    res = {}
    for cell in CELLS:
        base = ok[cell]["fullres"]
        bi = boot_idx[cell]
        per = {}
        for c in CAPS:
            a = ok[cell][c]
            d = a - base
            db = d[bi].mean(axis=1)
            lo, hi = np.percentile(db, [2.5, 97.5])
            per[c] = dict(acc=round(float(a.mean()), 4),
                          delta_vs_fullres=round(float(d.mean()), 4),
                          ci95=[round(float(lo), 4), round(float(hi), 4)],
                          significant=bool(lo > 0 or hi < 0),
                          max_pixels=CAP_MAXPX[c], vision_token_budget=CAP_TOKENS[c])
        res[cell] = dict(n=meta[cell]["n"], parse_ok=meta[cell]["parse_ok"],
                         gen_tokens_mean=meta[cell]["gen_tokens_mean"], by_cap=per)

    # ---- macro over the 7 INTERNAL cells (equal weight), bootstrapped on the shared streams
    macro = {}
    base_macro = np.zeros(NBOOT)
    for cell in CELLS:
        base_macro += ok[cell]["fullres"][boot_idx[cell]].mean(axis=1) / len(CELLS)
    for c in CAPS:
        pt = float(np.mean([ok[cell][c].mean() for cell in CELLS]))
        bm = np.zeros(NBOOT)
        for cell in CELLS:
            bm += ok[cell][c][boot_idx[cell]].mean(axis=1) / len(CELLS)
        d = bm - base_macro
        lo, hi = np.percentile(d, [2.5, 97.5])
        macro[c] = dict(macro7=round(pt, 4),
                        delta_vs_fullres=round(float(pt - np.mean(
                            [ok[cell]["fullres"].mean() for cell in CELLS])), 4),
                        ci95=[round(float(lo), 4), round(float(hi), 4)],
                        significant=bool(lo > 0 or hi < 0),
                        max_pixels=CAP_MAXPX[c], vision_token_budget=CAP_TOKENS[c])

    # ---- guardrail: how many of the 7 cells are significantly WORSE than fullres at each cap
    guard = {c: dict(
        n_cells_significantly_worse=sum(1 for cell in CELLS
                                        if res[cell]["by_cap"][c]["ci95"][1] < 0),
        n_cells_significantly_better=sum(1 for cell in CELLS
                                         if res[cell]["by_cap"][c]["ci95"][0] > 0),
        worst_cell_delta=min((res[cell]["by_cap"][c]["delta_vs_fullres"], cell)
                             for cell in CELLS)) for c in CAPS}

    out = dict(
        _what="ACCURACY half of the Attack-4 resolution frontier: Lingshu-7B direct MCQ, INTERNAL "
              "(MedVLThinker-Eval/NGC) harness, 5 resolution caps, 7 cells, perfectly paired on idx.",
        _source_dumps="ckpts/acc_gen/lingshu7b/{fullres,cap640,cap320,cap160,cap80}/"
                      "ckpt_<cell>_lingshu7b.jsonl -- produced by runners/run_lingshu_acc.sh "
                      "(src/labeling/run_vlm_eval.py, vLLM, tp=1, temperature 0, greedy). "
                      "NOT re-run here; read verbatim.",
        _track="INTERNAL harness (evaluation context B). NOT MedEvalKit. Its PMC-VQA is "
               "test_clean.csv (v1, n=2,000); the paper's macro cells use test_2.csv (v2, "
               "n=33,430) and the two splits share 6 items. DELTAS here are valid (matched arms, "
               "one script, one serving config, only max_pixels differs); LEVELS must never be "
               "compared against a macro-8 cell level.",
        _stats=dict(nboot=NBOOT, seed=SEED, method="paired item bootstrap, one shared resample "
                    "stream per cell reused across every cap so cap-to-cap comparisons are on "
                    "identical resamples"),
        _cap_definition="max_pixels/(28*28) is the merged vision-token budget for Qwen2.5-VL "
                        "(14x14 patches, 2x2 merge). cap320 == 320 vision tokens. MedEvalKit "
                        "(harness A) uses the qwen_vl_utils default 12,845,056 px = 16,384 tokens "
                        "= 12.8x this harness's own 'fullres' and 51.2x cap320.",
        per_cell=res, internal_track_macro7=macro, guardrail=guard)
    p = os.path.join(OUT, "accuracy_resolution_sweep.json")
    json.dump(out, open(p, "w"), indent=1)
    print(json.dumps(macro, indent=1))
    print(json.dumps(guard, indent=1))
    print("wrote", p)


if __name__ == "__main__":
    main()
