#!/bin/bash
# Attack B -- open-text generation for ONE arm of the cheap-leg probe.
#   $1 = model path (base snapshot, or the MERGED adapted checkpoint)
#   $2 = tag prefix (base7b | adapt7b_s0 | ...)
#   $3 = gpu id
#   $4 = vLLM gpu_memory_utilization (default 0.40)
# BOTH arms are generated by THIS script, so the serving configuration (vLLM, tp=1, cap320,
# max_model_len 4096, max_tokens 64, temp 0 greedy / temp 0.7 n=8, the same gpu_mem) is IDENTICAL
# between them.  That is mandatory: regenerating an open-text arm under a different configuration
# reproduces published cells only to ~+-0.008 per cell, larger than the effect being measured.
#
# THE GPUs ON THIS BOX ARE SHARED with another user's jobs, which appear and disappear and take up
# to 68 GB.  Every invocation therefore (a) waits until the device has enough free memory and
# (b) retries, and run_openvqa.py resumes from its own per-item JSONL, so a killed run loses nothing.
set -u
cd ~/medvlthinker-imgdiff-compute
export HF_HOME=/data/dan/hf_cache HF_HUB_OFFLINE=1 HF_HUB_DISABLE_XET=1
MP="$1"; TAG="$2"; GPU="$3"; GMEM="${4:-0.40}"
CKD="ckpts/openvqa/cheapleg_${TAG}"
NEED_MB=$(python3 -c "print(int(${GMEM}*81920)+3000)")
mkdir -p "$CKD" logs

wait_mem(){   # block until the device has NEED_MB free (or 90 min elapse)
  local t0=$SECONDS
  while :; do
    local used
    used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i "$GPU")
    local free=$((81920-used))
    [ "$free" -ge "$NEED_MB" ] && return 0
    [ $((SECONDS-t0)) -gt 21600 ] && { echo "WAIT_MEM_TIMEOUT gpu$GPU free=${free}MB"; return 1; }
    sleep 5
  done
}

run(){        # $1 dataset  $2 tag  $3 n_samples  $4 temp  $5 extra
  for try in $(seq 1 300); do
    wait_mem || return 1
    # shellcheck disable=SC2086
    CUDA_VISIBLE_DEVICES=$GPU python3 src/labeling/run_openvqa.py --model_path "$MP" --tag "$2" \
      --dataset "$1" --n_samples "$3" --temp "$4" --ckpt_dir "$CKD" --tp 1 --max_model_len 4096 \
      --gpu_mem "$GMEM" $5 && return 0
    echo "RETRY $1 tag=$2 (attempt $try failed) $(date)"
    sleep 10
  done
  echo "GIVEUP $1 tag=$2"; return 1
}

for ds in slake_open vqa_rad_open; do
  run "$ds" "$TAG"      1 0   ""
  run "$ds" "${TAG}_sc8" 8 0.7 ""
done
# PathVQA-open: the reported cell is the first 1500 items (run_openvqa.py --n 1500) -- the same
# sub-pool every published PathVQA-open number uses.
run pathvqa_open "$TAG"      1 0   "--n 1500"
run pathvqa_open "${TAG}_sc8" 8 0.7 "--n 1500"
echo "CHEAPLEG_OPEN_GEN_DONE $TAG $(date)"
