#!/bin/bash
# $1 = gpu id.  T = 0.0 (greedy) rung of the 2026-08-14 COLD temperature ladder.
#
# WHY THIS EXISTS SEPARATELY FROM run_sweep_adaptive.sh.
# vLLM 0.10.1.1 refuses n>1 with greedy sampling:
#     ValueError: n must be 1 when using greedy sampling, got 8.
# (measured 2026-08-14 07:14 UTC).  So the T=0 rung cannot be generated by the shared n=8 runner and is
# produced here at --n_samples 1 instead.  Three seeds are generated even though argmax decoding should
# be seed-independent: that is the DETERMINISM MEASUREMENT which licenses the statement "the 8-sample
# pool at T=0 holds exactly 1 distinct candidate".  No replicated draw is ever written to disk.
#
# Otherwise identical to run_sweep_adaptive.sh: polite on a shared GPU, never oversubscribes, never kills
# another process, resumable per item.
cd /home/jamesyang/medvlthinker-imgdiff-compute
export HF_HOME=/data/dan/hf_cache HF_HUB_OFFLINE=1 HF_HUB_DISABLE_XET=1
GPU=$1
SETTINGS=results/cascade_methods/artifacts/_decoding_ladder_cold_settings_T00.json
NEED_GIB=17            # 7B bf16 weights are 15.6 GiB; below this nothing can run
TOTAL_GIB=79

for attempt in $(seq 1 400); do
  for w in $(seq 1 240); do
    FREE_MIB=$(nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i "$GPU")
    FREE_GIB=$((FREE_MIB / 1024))
    if [ "$FREE_GIB" -ge "$NEED_GIB" ]; then break; fi
    echo "waiting for gpu$GPU: ${FREE_GIB}GiB free < ${NEED_GIB}GiB needed ($(date +%H:%M:%S))"
    sleep 20
  done
  USE_GIB=$((FREE_GIB - 1))
  if [ "$USE_GIB" -gt 40 ]; then USE_GIB=40; fi
  MEM=$(python3 -c "print(round($USE_GIB/$TOTAL_GIB, 3))")
  EXTRA=""
  if [ "$USE_GIB" -lt 22 ]; then EXTRA="--enforce_eager --max_model_len 1024"; fi
  echo "=== greedy attempt $attempt gpu$GPU mem=$MEM (${FREE_GIB}GiB free) $EXTRA $(date) ==="
  CUDA_VISIBLE_DEVICES=$GPU python3 src/cascade_methods/decoding_sweep_gen.py \
      --settings "$SETTINGS" --out ckpts/openvqa/decoding_sweep --gpu_mem "$MEM" \
      --n_samples 1 $EXTRA
  rc=$?
  if [ $rc -eq 0 ]; then echo "LADDER_GREEDY_GPU${GPU}_ALL_DONE"; break; fi
  echo "--- exit $rc, waiting 20s then resuming ---"
  sleep 20
done
